#pragma xidlc package xidlc
#pragma xidlc version v1.0.0

interface HttpMediaService {
    @post
    @request("urlencoded")
    string submit_form(
        string name,
        uint32 age
    );
    @post
    @response("msgpack")
    string fetch_msgpack(
        @query
        string id
    );
};
