#pragma xidlc service http://127.0.0.1:8080 dev server

interface HttpBidiStreamService {
    @bidi_stream
    @path("/chat")
    void chat(
        in string room,
        in string text,
        out string from,
        out string reply
    );
};
