#pragma xidlc package xidlc
#pragma xidlc version v1.0.0

@rust_allow(async_fn_in_trait)
interface RustHttp {
    @get(path = "/users/{user_id}")
    @rust_cfg(feature = "server")
    string get_user(
        @path
        uint32 user_id
    );
    @rust_cfg(feature = "server")
    attribute string display_name;
};
