module test {
    enum Status {
        @name("ok")
        OK,
        FAILED
    };

    struct User {
        uint32 id;
        @name("full_name")
        string name;
        Status status;
    };

    interface HeaderService {
        @get(path = "/v1/headers/{id}")
        User get_user(
            @path @rename("id")
            uint32 id,
            @header @rename("X-Req-Id")
            string req_id,
            @header @rename("X-Flags")
            sequence<string> flags,
            @header @rename("X-Age")
            uint32 age,
            @cookie @rename("sid")
            string session_id,
            @cookie @rename("pref")
            sequence<string> prefs
        );
        @post(path = "/v1/headers")
        void create_user(
            @header @rename("X-Token")
            string token,
            @cookie @rename("sid")
            string session_id,
            string name
        );
    };

};
