#pragma xidlc package xidlc
#pragma xidlc version v1.0.0

interface HttpCatchAllService {
    @get(path = "/files/{*path}")
    string read_file(
        @path @rename("path") string rel_path
    );

    @get(path = "/assets/{*key}")
    string read_asset(
        @path @rename("key") string key,
        @query @rename("v") string version
    );
};
