use crate::generate::render_const_expr;
use serde_json::json;
use xidl_parser::hir;

pub fn cpp_header() -> String {
    [
        "// Generated by idlc",
        "#pragma once",
        "#include \"xidl_xcdr.hpp\"",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <exception>",
        "#include <map>",
        "#include <memory>",
        "#include <string>",
        "#include <vector>",
    ]
    .join("\n")
}

pub fn cpp_source_header(header_name: &str) -> String {
    format!("#include \"{header_name}\"")
}

pub fn cpp_scoped_name(value: &hir::ScopedName) -> String {
    let name = value.name.join("::");
    if value.is_root {
        format!("::{name}")
    } else {
        name
    }
}

pub fn cpp_integer_type(value: &hir::IntegerType) -> String {
    match value {
        hir::IntegerType::Char => "int8_t".to_string(),
        hir::IntegerType::UChar => "uint8_t".to_string(),
        hir::IntegerType::U8 => "uint8_t".to_string(),
        hir::IntegerType::U16 => "uint16_t".to_string(),
        hir::IntegerType::U32 => "uint32_t".to_string(),
        hir::IntegerType::U64 => "uint64_t".to_string(),
        hir::IntegerType::I8 => "int8_t".to_string(),
        hir::IntegerType::I16 => "int16_t".to_string(),
        hir::IntegerType::I32 => "int32_t".to_string(),
        hir::IntegerType::I64 => "int64_t".to_string(),
    }
}

pub fn cpp_const_type(ty: &hir::ConstType) -> String {
    match ty {
        hir::ConstType::IntegerType(value) => cpp_integer_type(value),
        hir::ConstType::FloatingPtType => "double".to_string(),
        hir::ConstType::FixedPtConstType => "long double".to_string(),
        hir::ConstType::CharType => "char".to_string(),
        hir::ConstType::WideCharType => "wchar_t".to_string(),
        hir::ConstType::BooleanType => "bool".to_string(),
        hir::ConstType::OctetType => "uint8_t".to_string(),
        hir::ConstType::StringType(_) => "std::string".to_string(),
        hir::ConstType::WideStringType(_) => "std::wstring".to_string(),
        hir::ConstType::ScopedName(value) => cpp_scoped_name(value),
        hir::ConstType::SequenceType(_) => "void*".to_string(),
    }
}

pub fn cpp_type(ty: &hir::TypeSpec) -> String {
    match ty {
        hir::TypeSpec::SimpleTypeSpec(simple) => match simple {
            hir::SimpleTypeSpec::IntegerType(value) => cpp_integer_type(value),
            hir::SimpleTypeSpec::FloatingPtType => "double".to_string(),
            hir::SimpleTypeSpec::CharType => "char".to_string(),
            hir::SimpleTypeSpec::WideCharType => "wchar_t".to_string(),
            hir::SimpleTypeSpec::Boolean => "bool".to_string(),
            hir::SimpleTypeSpec::AnyType => "void*".to_string(),
            hir::SimpleTypeSpec::ObjectType => "void*".to_string(),
            hir::SimpleTypeSpec::ValueBaseType => "void*".to_string(),
            hir::SimpleTypeSpec::ScopedName(value) => cpp_scoped_name(value),
        },
        hir::TypeSpec::TemplateTypeSpec(template) => match template {
            hir::TemplateTypeSpec::SequenceType(seq) => {
                format!("std::vector<{}>", cpp_type(&seq.ty))
            }
            hir::TemplateTypeSpec::StringType(_) => "std::string".to_string(),
            hir::TemplateTypeSpec::WideStringType(_) => "std::wstring".to_string(),
            hir::TemplateTypeSpec::FixedPtType(_) => "long double".to_string(),
            hir::TemplateTypeSpec::MapType(map) => {
                format!("std::map<{}, {}>", cpp_type(&map.key), cpp_type(&map.value))
            }
        },
    }
}

pub fn cpp_switch_type(value: &hir::SwitchTypeSpec) -> String {
    match value {
        hir::SwitchTypeSpec::IntegerType(ty) => cpp_integer_type(ty),
        hir::SwitchTypeSpec::CharType => "char".to_string(),
        hir::SwitchTypeSpec::WideCharType => "wchar_t".to_string(),
        hir::SwitchTypeSpec::BooleanType => "bool".to_string(),
        hir::SwitchTypeSpec::ScopedName(value) => cpp_scoped_name(value),
        hir::SwitchTypeSpec::OctetType => "uint8_t".to_string(),
    }
}

pub fn cpp_literal(value: &hir::Literal) -> String {
    match value {
        hir::Literal::IntegerLiteral(lit) => match lit {
            hir::IntegerLiteral::BinNumber(value) => value.clone(),
            hir::IntegerLiteral::OctNumber(value) => value.clone(),
            hir::IntegerLiteral::DecNumber(value) => value.clone(),
            hir::IntegerLiteral::HexNumber(value) => value.clone(),
        },
        hir::Literal::FloatingPtLiteral(lit) => {
            let sign = lit
                .sign
                .as_ref()
                .map(|value| value.0.as_str())
                .unwrap_or("");
            format!("{}{}.{}", sign, lit.integer.0, lit.fraction.0)
        }
        hir::Literal::CharLiteral(value) => value.clone(),
        hir::Literal::WideCharacterLiteral(value) => value.clone(),
        hir::Literal::StringLiteral(value) => value.clone(),
        hir::Literal::WideStringLiteral(value) => value.clone(),
        hir::Literal::BooleanLiteral(value) => value.to_ascii_lowercase(),
    }
}

pub fn render_const(expr: &hir::ConstExpr) -> String {
    render_const_expr(expr, &cpp_scoped_name, &cpp_literal)
}

pub fn array_type(base: &str, dims: &[String]) -> String {
    let mut out = base.to_string();
    for dim in dims.iter().rev() {
        out = format!("std::array<{}, {}>", out, dim);
    }
    out
}

pub fn apply_declarator(base: &str, decl: &hir::Declarator) -> String {
    let dims = declarator_dims(decl);
    if dims.is_empty() {
        base.to_string()
    } else {
        array_type(base, &dims)
    }
}

pub fn type_with_decl(ty: &hir::TypeSpec, decl: &hir::Declarator) -> String {
    let base = cpp_type(ty);
    apply_declarator(&base, decl)
}

pub fn declarator_dims(decl: &hir::Declarator) -> Vec<String> {
    match decl {
        hir::Declarator::SimpleDeclarator(_) => Vec::new(),
        hir::Declarator::ArrayDeclarator(value) => {
            value.len.iter().map(|len| render_const(&len.0)).collect()
        }
    }
}

pub fn declarator_name(decl: &hir::Declarator) -> String {
    match decl {
        hir::Declarator::SimpleDeclarator(value) => value.0.clone(),
        hir::Declarator::ArrayDeclarator(value) => value.ident.clone(),
    }
}

pub fn member_json(ty: &hir::TypeSpec, decl: &hir::Declarator) -> serde_json::Value {
    let name = declarator_name(decl);
    let ty = type_with_decl(ty, decl);
    json!({ "ty": ty, "name": name })
}

pub fn typedef_json(base: &str, decl: &hir::Declarator) -> serde_json::Value {
    let name = declarator_name(decl);
    let ty = apply_declarator(base, decl);
    json!({ "ty": ty, "name": name })
}

pub fn bitfield_type(value: &hir::BitFieldType) -> String {
    match value {
        hir::BitFieldType::Bool => "bool".to_string(),
        hir::BitFieldType::Octec => "uint8_t".to_string(),
        hir::BitFieldType::SignedInt => "int32_t".to_string(),
        hir::BitFieldType::UnsignedInt => "uint32_t".to_string(),
    }
}

pub fn collect_inline_defs(
    constr: &hir::ConstrTypeDcl,
    renderer: &crate::generate::cpp::CppRenderer,
) -> crate::error::IdlcResult<crate::generate::cpp::CppRenderOutput> {
    use crate::generate::cpp::CppRender;
    match constr {
        hir::ConstrTypeDcl::StructDcl(def) => def.render(renderer),
        hir::ConstrTypeDcl::EnumDcl(def) => def.render(renderer),
        hir::ConstrTypeDcl::UnionDef(def) => def.render(renderer),
        hir::ConstrTypeDcl::BitsetDcl(def) => def.render(renderer),
        hir::ConstrTypeDcl::BitmaskDcl(def) => def.render(renderer),
        _ => Ok(crate::generate::cpp::CppRenderOutput::default()),
    }
}

pub fn kind_json(kind: &str) -> serde_json::Value {
    json!({ "kind": kind })
}
