# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(tests/snapshots)|(xidl-xcdr/include/xidl_xcdr.h)|(.*.snap)|(xidlc-examples/api/.*.json)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        language: system
        types_or: [rust]
        entry: cargo fmt
        files: \.rs$
        pass_filenames: false

  - repo: local
    hooks:
      - id: toml
        name: toml
        language: system
        types_or: [toml]
        entry: taplo format

  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.4.0"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@2.2.6"]
        exclude: "CHANGELOG.md"
