site_name: XIDL

nav:
  - Home: index.md
  - RFC:
      - HTTP: rfc/http.md
      - HTTP Stream: rfc/http-stream.md
      - JSONRPC: rfc/jsonrpc.md
      - JSONRPC Stream: rfc/jsonrpc-stream.md
  - XIDLC:
      - axum: rust-axum.md
      - rust-jsonrpc: rust-jsonrpc.md
      - OpenAPI: openapi.md
  - Compiler Extension: pragma.md
  - Plugin Development: plugin.md

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - callouts
  - github-callouts
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - include-markdown:
      preserve_includer_indent: false
  - kroki:
      file_types:
        - svg
      fence_prefix: ""
      enable_diagramsnet: true
