site_name: XIDL
site_url: https://xidl.github.io/xidl/
repo_url: https://github.com/xidl/xidl

nav:
  - Overview: index.md
  - Axum: rust-axum.md
  - RUST-JSONRPC: rust-jsonrpc.md
  - OpenAPI: openapi.md

  - RFC:
      - HTTP: rfc/http.md
      - HTTP Stream: rfc/http-stream.md
      - JSONRPC: rfc/jsonrpc.md
      - JSONRPC Stream: rfc/jsonrpc-stream.md
  - Development:
      - Plugin Development: plugin.md
      - Compiler Spec: architecture.md
      - Compiler Extensions: pragma.md

theme:
  name: material
  language: en
  features:
    - search.suggest
    - search.highlight
  logo: assets/log.png
  favicon: assets/log.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - callouts
  - github-callouts
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - include-markdown:
      preserve_includer_indent: false
  - kroki:
      file_types:
        - svg
      fence_prefix: ""
      enable_diagramsnet: true
