interface HelloWorld {
    @post(path = "/hello")
    void sayHello(
        in string name
    );

};

enum EnumFirstDefault {
    First
};

enum EnumSecondDefault {
    First,
    @default_literal
    Second
};
