interface Codegen {
    ::xidl_parser::hir::ParserProperties get_properties();
    sequence<::xidlc::generate::Artifact> generate(
        in ::xidl_parser::hir::Specification hir,
        in string input
    );
};
