/// Generated by xidlc 0.50.2 at 2026-05-03 11:10.
#[async_trait::async_trait]
pub trait Codegen {
    async fn get_engine_version<'a>(&'a self) -> Result<String, xidl_jsonrpc::Error>;
    async fn get_properties<'a>(
        &'a self,
    ) -> Result<::xidl_parser::hir::ParserProperties, xidl_jsonrpc::Error>;
    async fn generate<'a>(
        &'a self,
        input: CodegenInput,
        path: String,
        props: ::xidl_parser::hir::ParserProperties,
    ) -> Result<Vec<Artifact>, xidl_jsonrpc::Error>;
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
struct CodegengetEngineVersionParams {}
#[derive(::serde::Serialize, ::serde::Deserialize)]
struct CodegengetPropertiesParams {}
#[derive(::serde::Serialize, ::serde::Deserialize)]
struct CodegengenerateParams {
    input: CodegenInput,
    path: String,
    props: ::xidl_parser::hir::ParserProperties,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
pub struct CodegengetEngineVersionResult {
    #[serde(rename = "return")]
    pub r#return: String,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
pub struct CodegengetPropertiesResult {
    #[serde(rename = "return")]
    pub r#return: ::xidl_parser::hir::ParserProperties,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
pub struct CodegengenerateResult {
    #[serde(rename = "return")]
    pub r#return: Vec<Artifact>,
}
pub struct CodegenServer<T> {
    inner: T,
}
impl<T> CodegenServer<T> {
    pub fn new(inner: T) -> Self {
        Self { inner }
    }
}
#[async_trait::async_trait]
impl<T> xidl_jsonrpc::Handler for CodegenServer<T>
where
    T: Codegen + Send + Sync,
{
    #[allow(clippy::match_single_binding)]
    async fn handle(
        &self,
        method: &str,
        params: ::serde_json::Value,
    ) -> Result<::serde_json::Value, xidl_jsonrpc::Error> {
        match method {
            "Codegen.get_engine_version" => {
                let params: CodegengetEngineVersionParams = ::serde_json::from_value(
                        params,
                    )
                    .map_err(|err| xidl_jsonrpc::Error::invalid_params(
                        err.to_string(),
                    ))?;
                let result = self.inner.get_engine_version().await?;
                let wire = CodegengetEngineVersionResult {
                    r#return: result,
                };
                Ok(::serde_json::to_value(wire)?)
            }
            "Codegen.get_properties" => {
                let params: CodegengetPropertiesParams = ::serde_json::from_value(params)
                    .map_err(|err| xidl_jsonrpc::Error::invalid_params(
                        err.to_string(),
                    ))?;
                let result = self.inner.get_properties().await?;
                let wire = CodegengetPropertiesResult {
                    r#return: result,
                };
                Ok(::serde_json::to_value(wire)?)
            }
            "Codegen.generate" => {
                let params: CodegengenerateParams = ::serde_json::from_value(params)
                    .map_err(|err| xidl_jsonrpc::Error::invalid_params(
                        err.to_string(),
                    ))?;
                let result = self
                    .inner
                    .generate(params.input, params.path, params.props)
                    .await?;
                let wire = CodegengenerateResult {
                    r#return: result,
                };
                Ok(::serde_json::to_value(wire)?)
            }
            _ => Err(xidl_jsonrpc::Error::method_not_found(method)),
        }
    }
    fn accepts_bidi(&self, method: &str) -> bool {
        false
    }
    #[allow(clippy::match_single_binding)]
    async fn handle_bidi(
        &self,
        method: &str,
        params: ::serde_json::Value,
        mut stream: xidl_jsonrpc::stream::ReaderWriter<
            ::serde_json::Value,
            ::serde_json::Value,
        >,
    ) -> Result<(), xidl_jsonrpc::Error> {
        match method {
            _ => Err(xidl_jsonrpc::Error::method_not_found(method)),
        }
    }
}
pub struct CodegenClient<S> {
    client: std::sync::Arc<tokio::sync::Mutex<xidl_jsonrpc::Client<S>>>,
    endpoint: Option<String>,
}
type CodegenTransport = Box<
    dyn xidl_jsonrpc::transport::Stream + Unpin + Send + 'static,
>;
pub struct CodegenClientBuilder {
    endpoint: Option<String>,
}
impl Default for CodegenClientBuilder {
    fn default() -> Self {
        Self::new()
    }
}
impl CodegenClientBuilder {
    pub fn new() -> Self {
        Self { endpoint: None }
    }
    pub fn with_endpoint(mut self, endpoint: impl Into<String>) -> Self {
        self.endpoint = Some(endpoint.into());
        self
    }
    pub async fn build(
        self,
    ) -> Result<CodegenClient<CodegenTransport>, xidl_jsonrpc::Error> {
        let endpoint = self
            .endpoint
            .ok_or(xidl_jsonrpc::Error::Protocol("missing endpoint"))?;
        let stream = xidl_jsonrpc::connect(&endpoint)
            .await
            .map_err(xidl_jsonrpc::Error::Io)?;
        Ok(CodegenClient::from_stream(stream, Some(endpoint)))
    }
}
impl CodegenClient<CodegenTransport> {
    pub fn builder() -> CodegenClientBuilder {
        CodegenClientBuilder::new()
    }
}
impl<S> CodegenClient<S>
where
    S: xidl_jsonrpc::Stream + Unpin + Send + 'static,
{
    pub fn new(stream: S) -> Self {
        Self::from_stream(stream, None)
    }
    fn from_stream(stream: S, endpoint: Option<String>) -> Self {
        Self {
            client: std::sync::Arc::new(
                tokio::sync::Mutex::new(xidl_jsonrpc::Client::new(stream)),
            ),
            endpoint,
        }
    }
}
#[async_trait::async_trait]
impl<S> Codegen for CodegenClient<S>
where
    S: xidl_jsonrpc::Stream + Unpin + Send + 'static,
{
    async fn get_engine_version(&self) -> Result<String, xidl_jsonrpc::Error> {
        let params = CodegengetEngineVersionParams {};
        let mut client = self.client.lock().await;
        let result: CodegengetEngineVersionResult = client
            .call("Codegen.get_engine_version", params)
            .await?;
        Ok(result.r#return)
    }
    async fn get_properties(
        &self,
    ) -> Result<::xidl_parser::hir::ParserProperties, xidl_jsonrpc::Error> {
        let params = CodegengetPropertiesParams {};
        let mut client = self.client.lock().await;
        let result: CodegengetPropertiesResult = client
            .call("Codegen.get_properties", params)
            .await?;
        Ok(result.r#return)
    }
    async fn generate(
        &self,
        input: CodegenInput,
        path: String,
        props: ::xidl_parser::hir::ParserProperties,
    ) -> Result<Vec<Artifact>, xidl_jsonrpc::Error> {
        let params = CodegengenerateParams {
            input,
            path,
            props,
        };
        let mut client = self.client.lock().await;
        let result: CodegengenerateResult = client
            .call("Codegen.generate", params)
            .await?;
        Ok(result.r#return)
    }
}
impl<S> CodegenClient<S>
where
    S: xidl_jsonrpc::Stream + Unpin + Send + 'static,
{}
#[derive(Debug, ::serde::Serialize, ::serde::Deserialize)]
pub struct ArtifactHir {
    pub lang: String,
    pub hir: ::xidl_parser::hir::Specification,
    pub props: ::xidl_parser::hir::ParserProperties,
}
impl ArtifactHir {}
#[derive(Debug, ::serde::Serialize, ::serde::Deserialize)]
pub struct ArtifactRestHir {
    pub lang: String,
    pub rest_hir: ::xidl_parser::rest_hir::RestHirDocument,
    pub props: ::xidl_parser::hir::ParserProperties,
}
impl ArtifactRestHir {}
#[derive(Debug, ::serde::Serialize, ::serde::Deserialize)]
pub struct ArtifactJsonRpcHir {
    pub lang: String,
    pub jsonrpc_hir: ::xidl_parser::jsonrpc_hir::JsonRpcHirDocument,
    pub props: ::xidl_parser::hir::ParserProperties,
}
impl ArtifactJsonRpcHir {}
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    ::serde::Serialize,
    ::serde::Deserialize,
    Default,
)]
pub enum CodegenInputKind {
    #[default]
    RpcHir,
    RestHir,
    JsonRpcHir,
}
pub struct CodegenInput {
    tag: CodegenInputKind,
    data: CodegenInputData,
}
union CodegenInputData {
    rpc_hir: core::mem::ManuallyDrop<::xidl_parser::hir::Specification>,
    rest_hir: core::mem::ManuallyDrop<::xidl_parser::rest_hir::RestHirDocument>,
    jsonrpc_hir: core::mem::ManuallyDrop<::xidl_parser::jsonrpc_hir::JsonRpcHirDocument>,
}
impl Drop for CodegenInput {
    fn drop(&mut self) {
        match self.tag {
            CodegenInputKind::RpcHir => {
                unsafe {
                    core::mem::ManuallyDrop::drop(&mut self.data.rpc_hir);
                }
            }
            CodegenInputKind::RestHir => {
                unsafe {
                    core::mem::ManuallyDrop::drop(&mut self.data.rest_hir);
                }
            }
            CodegenInputKind::JsonRpcHir => {
                unsafe {
                    core::mem::ManuallyDrop::drop(&mut self.data.jsonrpc_hir);
                }
            }
        }
    }
}
impl CodegenInput {
    pub fn new_rpc_hir(value: ::xidl_parser::hir::Specification) -> Self {
        Self {
            tag: CodegenInputKind::RpcHir,
            data: CodegenInputData {
                rpc_hir: core::mem::ManuallyDrop::new(value),
            },
        }
    }
    pub fn is_rpc_hir(&self) -> bool {
        matches!(self.tag, CodegenInputKind::RpcHir)
    }
    pub fn as_rpc_hir(&self) -> &::xidl_parser::hir::Specification {
        debug_assert!(self.is_rpc_hir());
        unsafe { &self.data.rpc_hir }
    }
    pub fn as_rpc_hir_mut(&mut self) -> &mut ::xidl_parser::hir::Specification {
        debug_assert!(self.is_rpc_hir());
        unsafe { &mut self.data.rpc_hir }
    }
    pub fn into_rpc_hir(self) -> ::xidl_parser::hir::Specification {
        debug_assert!(self.is_rpc_hir());
        unsafe {
            let mut forget = core::mem::ManuallyDrop::new(self);
            core::mem::ManuallyDrop::take(&mut forget.data.rpc_hir)
        }
    }
    pub fn new_rest_hir(value: ::xidl_parser::rest_hir::RestHirDocument) -> Self {
        Self {
            tag: CodegenInputKind::RestHir,
            data: CodegenInputData {
                rest_hir: core::mem::ManuallyDrop::new(value),
            },
        }
    }
    pub fn is_rest_hir(&self) -> bool {
        matches!(self.tag, CodegenInputKind::RestHir)
    }
    pub fn as_rest_hir(&self) -> &::xidl_parser::rest_hir::RestHirDocument {
        debug_assert!(self.is_rest_hir());
        unsafe { &self.data.rest_hir }
    }
    pub fn as_rest_hir_mut(&mut self) -> &mut ::xidl_parser::rest_hir::RestHirDocument {
        debug_assert!(self.is_rest_hir());
        unsafe { &mut self.data.rest_hir }
    }
    pub fn into_rest_hir(self) -> ::xidl_parser::rest_hir::RestHirDocument {
        debug_assert!(self.is_rest_hir());
        unsafe {
            let mut forget = core::mem::ManuallyDrop::new(self);
            core::mem::ManuallyDrop::take(&mut forget.data.rest_hir)
        }
    }
    pub fn new_jsonrpc_hir(
        value: ::xidl_parser::jsonrpc_hir::JsonRpcHirDocument,
    ) -> Self {
        Self {
            tag: CodegenInputKind::JsonRpcHir,
            data: CodegenInputData {
                jsonrpc_hir: core::mem::ManuallyDrop::new(value),
            },
        }
    }
    pub fn is_jsonrpc_hir(&self) -> bool {
        matches!(self.tag, CodegenInputKind::JsonRpcHir)
    }
    pub fn as_jsonrpc_hir(&self) -> &::xidl_parser::jsonrpc_hir::JsonRpcHirDocument {
        debug_assert!(self.is_jsonrpc_hir());
        unsafe { &self.data.jsonrpc_hir }
    }
    pub fn as_jsonrpc_hir_mut(
        &mut self,
    ) -> &mut ::xidl_parser::jsonrpc_hir::JsonRpcHirDocument {
        debug_assert!(self.is_jsonrpc_hir());
        unsafe { &mut self.data.jsonrpc_hir }
    }
    pub fn into_jsonrpc_hir(self) -> ::xidl_parser::jsonrpc_hir::JsonRpcHirDocument {
        debug_assert!(self.is_jsonrpc_hir());
        unsafe {
            let mut forget = core::mem::ManuallyDrop::new(self);
            core::mem::ManuallyDrop::take(&mut forget.data.jsonrpc_hir)
        }
    }
    pub fn tag(&self) -> &CodegenInputKind {
        &self.tag
    }
}
impl serde::Serialize for CodegenInput {
    fn serialize<__S>(
        &self,
        __serializer: __S,
    ) -> serde::__private228::Result<__S::Ok, __S::Error>
    where
        __S: serde::Serializer,
    {
        match self.tag {
            CodegenInputKind::RpcHir => {
                let mut s = serde::Serializer::serialize_struct_variant(
                    __serializer,
                    "CodegenInput",
                    0,
                    "CodegenInputKind::RpcHir",
                    size_of::<::xidl_parser::hir::Specification>(),
                )?;
                let x = unsafe { std::ops::Deref::deref(&self.data.rpc_hir) };
                serde::ser::SerializeStructVariant::serialize_field(
                    &mut s,
                    "CodegenInputKind::RpcHir",
                    x,
                )?;
                serde::ser::SerializeStructVariant::end(s)
            }
            CodegenInputKind::RestHir => {
                let mut s = serde::Serializer::serialize_struct_variant(
                    __serializer,
                    "CodegenInput",
                    1,
                    "CodegenInputKind::RestHir",
                    size_of::<::xidl_parser::rest_hir::RestHirDocument>(),
                )?;
                let x = unsafe { std::ops::Deref::deref(&self.data.rest_hir) };
                serde::ser::SerializeStructVariant::serialize_field(
                    &mut s,
                    "CodegenInputKind::RestHir",
                    x,
                )?;
                serde::ser::SerializeStructVariant::end(s)
            }
            CodegenInputKind::JsonRpcHir => {
                let mut s = serde::Serializer::serialize_struct_variant(
                    __serializer,
                    "CodegenInput",
                    2,
                    "CodegenInputKind::JsonRpcHir",
                    size_of::<::xidl_parser::jsonrpc_hir::JsonRpcHirDocument>(),
                )?;
                let x = unsafe { std::ops::Deref::deref(&self.data.jsonrpc_hir) };
                serde::ser::SerializeStructVariant::serialize_field(
                    &mut s,
                    "CodegenInputKind::JsonRpcHir",
                    x,
                )?;
                serde::ser::SerializeStructVariant::end(s)
            }
        }
    }
}
impl<'de> serde::Deserialize<'de> for CodegenInput {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        const VARIANTS: &[&str] = &[
            "CodegenInputKind::RpcHir",
            "CodegenInputKind::RestHir",
            "CodegenInputKind::JsonRpcHir",
        ];
        enum __Variant {
            __Case0,
            __Case1,
            __Case2,
        }
        impl<'de> serde::Deserialize<'de> for __Variant {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where
                D: serde::Deserializer<'de>,
            {
                struct __VariantVisitor;
                impl serde::de::Visitor<'_> for __VariantVisitor {
                    type Value = __Variant;
                    fn expecting(
                        &self,
                        formatter: &mut core::fmt::Formatter,
                    ) -> core::fmt::Result {
                        formatter.write_str("union variant")
                    }
                    fn visit_str<E>(self, value: &str) -> Result<Self::Value, E>
                    where
                        E: serde::de::Error,
                    {
                        match value {
                            "CodegenInputKind::RpcHir" => Ok(__Variant::__Case0),
                            "CodegenInputKind::RestHir" => Ok(__Variant::__Case1),
                            "CodegenInputKind::JsonRpcHir" => Ok(__Variant::__Case2),
                            _ => Err(E::unknown_variant(value, VARIANTS)),
                        }
                    }
                }
                deserializer.deserialize_identifier(__VariantVisitor)
            }
        }
        struct __Visitor;
        impl<'de> serde::de::Visitor<'de> for __Visitor {
            type Value = CodegenInput;
            fn expecting(
                &self,
                formatter: &mut core::fmt::Formatter,
            ) -> core::fmt::Result {
                formatter.write_str("externally tagged union CodegenInput")
            }
            fn visit_enum<A>(self, data: A) -> Result<Self::Value, A::Error>
            where
                A: serde::de::EnumAccess<'de>,
            {
                let (variant, variant_access) = data.variant::<__Variant>()?;
                match variant {
                    __Variant::__Case0 => {
                        struct __CaseVisitor;
                        impl<'de> serde::de::Visitor<'de> for __CaseVisitor {
                            type Value = ::xidl_parser::hir::Specification;
                            fn expecting(
                                &self,
                                formatter: &mut core::fmt::Formatter,
                            ) -> core::fmt::Result {
                                formatter
                                    .write_str("struct variant CodegenInputKind::RpcHir")
                            }
                            fn visit_map<M>(
                                self,
                                mut map: M,
                            ) -> Result<Self::Value, M::Error>
                            where
                                M: serde::de::MapAccess<'de>,
                            {
                                let mut value = None;
                                while let Some(key) = map.next_key::<String>()? {
                                    if key == "CodegenInputKind::RpcHir" {
                                        if value.is_some() {
                                            return Err(
                                                serde::de::Error::duplicate_field(
                                                    "CodegenInputKind::RpcHir",
                                                ),
                                            );
                                        }
                                        value = Some(map.next_value()?);
                                    } else {
                                        let _: serde::de::IgnoredAny = map.next_value()?;
                                    }
                                }
                                value
                                    .ok_or_else(|| {
                                        serde::de::Error::missing_field("CodegenInputKind::RpcHir")
                                    })
                            }
                        }
                        let value = serde::de::VariantAccess::struct_variant(
                            variant_access,
                            &["CodegenInputKind::RpcHir"],
                            __CaseVisitor,
                        )?;
                        let tag = CodegenInputKind::RpcHir;
                        Ok(CodegenInput {
                            tag,
                            data: CodegenInputData {
                                rpc_hir: core::mem::ManuallyDrop::new(value),
                            },
                        })
                    }
                    __Variant::__Case1 => {
                        struct __CaseVisitor;
                        impl<'de> serde::de::Visitor<'de> for __CaseVisitor {
                            type Value = ::xidl_parser::rest_hir::RestHirDocument;
                            fn expecting(
                                &self,
                                formatter: &mut core::fmt::Formatter,
                            ) -> core::fmt::Result {
                                formatter
                                    .write_str("struct variant CodegenInputKind::RestHir")
                            }
                            fn visit_map<M>(
                                self,
                                mut map: M,
                            ) -> Result<Self::Value, M::Error>
                            where
                                M: serde::de::MapAccess<'de>,
                            {
                                let mut value = None;
                                while let Some(key) = map.next_key::<String>()? {
                                    if key == "CodegenInputKind::RestHir" {
                                        if value.is_some() {
                                            return Err(
                                                serde::de::Error::duplicate_field(
                                                    "CodegenInputKind::RestHir",
                                                ),
                                            );
                                        }
                                        value = Some(map.next_value()?);
                                    } else {
                                        let _: serde::de::IgnoredAny = map.next_value()?;
                                    }
                                }
                                value
                                    .ok_or_else(|| {
                                        serde::de::Error::missing_field("CodegenInputKind::RestHir")
                                    })
                            }
                        }
                        let value = serde::de::VariantAccess::struct_variant(
                            variant_access,
                            &["CodegenInputKind::RestHir"],
                            __CaseVisitor,
                        )?;
                        let tag = CodegenInputKind::RestHir;
                        Ok(CodegenInput {
                            tag,
                            data: CodegenInputData {
                                rest_hir: core::mem::ManuallyDrop::new(value),
                            },
                        })
                    }
                    __Variant::__Case2 => {
                        struct __CaseVisitor;
                        impl<'de> serde::de::Visitor<'de> for __CaseVisitor {
                            type Value = ::xidl_parser::jsonrpc_hir::JsonRpcHirDocument;
                            fn expecting(
                                &self,
                                formatter: &mut core::fmt::Formatter,
                            ) -> core::fmt::Result {
                                formatter
                                    .write_str("struct variant CodegenInputKind::JsonRpcHir")
                            }
                            fn visit_map<M>(
                                self,
                                mut map: M,
                            ) -> Result<Self::Value, M::Error>
                            where
                                M: serde::de::MapAccess<'de>,
                            {
                                let mut value = None;
                                while let Some(key) = map.next_key::<String>()? {
                                    if key == "CodegenInputKind::JsonRpcHir" {
                                        if value.is_some() {
                                            return Err(
                                                serde::de::Error::duplicate_field(
                                                    "CodegenInputKind::JsonRpcHir",
                                                ),
                                            );
                                        }
                                        value = Some(map.next_value()?);
                                    } else {
                                        let _: serde::de::IgnoredAny = map.next_value()?;
                                    }
                                }
                                value
                                    .ok_or_else(|| {
                                        serde::de::Error::missing_field(
                                            "CodegenInputKind::JsonRpcHir",
                                        )
                                    })
                            }
                        }
                        let value = serde::de::VariantAccess::struct_variant(
                            variant_access,
                            &["CodegenInputKind::JsonRpcHir"],
                            __CaseVisitor,
                        )?;
                        let tag = CodegenInputKind::JsonRpcHir;
                        Ok(CodegenInput {
                            tag,
                            data: CodegenInputData {
                                jsonrpc_hir: core::mem::ManuallyDrop::new(value),
                            },
                        })
                    }
                }
            }
        }
        deserializer.deserialize_enum("CodegenInput", VARIANTS, __Visitor)
    }
}
#[derive(Debug, ::serde::Serialize, ::serde::Deserialize)]
pub struct ArtifactFile {
    pub path: String,
    pub content: String,
}
impl ArtifactFile {}
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    ::serde::Serialize,
    ::serde::Deserialize,
    Default,
)]
pub enum ArtifactKind {
    #[default]
    Hir,
    RestHir,
    JsonRpcHir,
    File,
}
pub struct Artifact {
    tag: ArtifactKind,
    data: ArtifactData,
}
union ArtifactData {
    hir: core::mem::ManuallyDrop<ArtifactHir>,
    rest_hir: core::mem::ManuallyDrop<ArtifactRestHir>,
    jsonrpc_hir: core::mem::ManuallyDrop<ArtifactJsonRpcHir>,
    file: core::mem::ManuallyDrop<ArtifactFile>,
}
impl Drop for Artifact {
    fn drop(&mut self) {
        match self.tag {
            ArtifactKind::Hir => {
                unsafe {
                    core::mem::ManuallyDrop::drop(&mut self.data.hir);
                }
            }
            ArtifactKind::RestHir => {
                unsafe {
                    core::mem::ManuallyDrop::drop(&mut self.data.rest_hir);
                }
            }
            ArtifactKind::JsonRpcHir => {
                unsafe {
                    core::mem::ManuallyDrop::drop(&mut self.data.jsonrpc_hir);
                }
            }
            ArtifactKind::File => {
                unsafe {
                    core::mem::ManuallyDrop::drop(&mut self.data.file);
                }
            }
        }
    }
}
impl Artifact {
    pub fn new_hir(value: ArtifactHir) -> Self {
        Self {
            tag: ArtifactKind::Hir,
            data: ArtifactData {
                hir: core::mem::ManuallyDrop::new(value),
            },
        }
    }
    pub fn is_hir(&self) -> bool {
        matches!(self.tag, ArtifactKind::Hir)
    }
    pub fn as_hir(&self) -> &ArtifactHir {
        debug_assert!(self.is_hir());
        unsafe { &self.data.hir }
    }
    pub fn as_hir_mut(&mut self) -> &mut ArtifactHir {
        debug_assert!(self.is_hir());
        unsafe { &mut self.data.hir }
    }
    pub fn into_hir(self) -> ArtifactHir {
        debug_assert!(self.is_hir());
        unsafe {
            let mut forget = core::mem::ManuallyDrop::new(self);
            core::mem::ManuallyDrop::take(&mut forget.data.hir)
        }
    }
    pub fn new_rest_hir(value: ArtifactRestHir) -> Self {
        Self {
            tag: ArtifactKind::RestHir,
            data: ArtifactData {
                rest_hir: core::mem::ManuallyDrop::new(value),
            },
        }
    }
    pub fn is_rest_hir(&self) -> bool {
        matches!(self.tag, ArtifactKind::RestHir)
    }
    pub fn as_rest_hir(&self) -> &ArtifactRestHir {
        debug_assert!(self.is_rest_hir());
        unsafe { &self.data.rest_hir }
    }
    pub fn as_rest_hir_mut(&mut self) -> &mut ArtifactRestHir {
        debug_assert!(self.is_rest_hir());
        unsafe { &mut self.data.rest_hir }
    }
    pub fn into_rest_hir(self) -> ArtifactRestHir {
        debug_assert!(self.is_rest_hir());
        unsafe {
            let mut forget = core::mem::ManuallyDrop::new(self);
            core::mem::ManuallyDrop::take(&mut forget.data.rest_hir)
        }
    }
    pub fn new_jsonrpc_hir(value: ArtifactJsonRpcHir) -> Self {
        Self {
            tag: ArtifactKind::JsonRpcHir,
            data: ArtifactData {
                jsonrpc_hir: core::mem::ManuallyDrop::new(value),
            },
        }
    }
    pub fn is_jsonrpc_hir(&self) -> bool {
        matches!(self.tag, ArtifactKind::JsonRpcHir)
    }
    pub fn as_jsonrpc_hir(&self) -> &ArtifactJsonRpcHir {
        debug_assert!(self.is_jsonrpc_hir());
        unsafe { &self.data.jsonrpc_hir }
    }
    pub fn as_jsonrpc_hir_mut(&mut self) -> &mut ArtifactJsonRpcHir {
        debug_assert!(self.is_jsonrpc_hir());
        unsafe { &mut self.data.jsonrpc_hir }
    }
    pub fn into_jsonrpc_hir(self) -> ArtifactJsonRpcHir {
        debug_assert!(self.is_jsonrpc_hir());
        unsafe {
            let mut forget = core::mem::ManuallyDrop::new(self);
            core::mem::ManuallyDrop::take(&mut forget.data.jsonrpc_hir)
        }
    }
    pub fn new_file(value: ArtifactFile) -> Self {
        Self {
            tag: ArtifactKind::File,
            data: ArtifactData {
                file: core::mem::ManuallyDrop::new(value),
            },
        }
    }
    pub fn is_file(&self) -> bool {
        matches!(self.tag, ArtifactKind::File)
    }
    pub fn as_file(&self) -> &ArtifactFile {
        debug_assert!(self.is_file());
        unsafe { &self.data.file }
    }
    pub fn as_file_mut(&mut self) -> &mut ArtifactFile {
        debug_assert!(self.is_file());
        unsafe { &mut self.data.file }
    }
    pub fn into_file(self) -> ArtifactFile {
        debug_assert!(self.is_file());
        unsafe {
            let mut forget = core::mem::ManuallyDrop::new(self);
            core::mem::ManuallyDrop::take(&mut forget.data.file)
        }
    }
    pub fn tag(&self) -> &ArtifactKind {
        &self.tag
    }
}
impl serde::Serialize for Artifact {
    fn serialize<__S>(
        &self,
        __serializer: __S,
    ) -> serde::__private228::Result<__S::Ok, __S::Error>
    where
        __S: serde::Serializer,
    {
        match self.tag {
            ArtifactKind::Hir => {
                let mut s = serde::Serializer::serialize_struct_variant(
                    __serializer,
                    "Artifact",
                    0,
                    "ArtifactKind::Hir",
                    size_of::<ArtifactHir>(),
                )?;
                let x = unsafe { std::ops::Deref::deref(&self.data.hir) };
                serde::ser::SerializeStructVariant::serialize_field(
                    &mut s,
                    "ArtifactKind::Hir",
                    x,
                )?;
                serde::ser::SerializeStructVariant::end(s)
            }
            ArtifactKind::RestHir => {
                let mut s = serde::Serializer::serialize_struct_variant(
                    __serializer,
                    "Artifact",
                    1,
                    "ArtifactKind::RestHir",
                    size_of::<ArtifactRestHir>(),
                )?;
                let x = unsafe { std::ops::Deref::deref(&self.data.rest_hir) };
                serde::ser::SerializeStructVariant::serialize_field(
                    &mut s,
                    "ArtifactKind::RestHir",
                    x,
                )?;
                serde::ser::SerializeStructVariant::end(s)
            }
            ArtifactKind::JsonRpcHir => {
                let mut s = serde::Serializer::serialize_struct_variant(
                    __serializer,
                    "Artifact",
                    2,
                    "ArtifactKind::JsonRpcHir",
                    size_of::<ArtifactJsonRpcHir>(),
                )?;
                let x = unsafe { std::ops::Deref::deref(&self.data.jsonrpc_hir) };
                serde::ser::SerializeStructVariant::serialize_field(
                    &mut s,
                    "ArtifactKind::JsonRpcHir",
                    x,
                )?;
                serde::ser::SerializeStructVariant::end(s)
            }
            ArtifactKind::File => {
                let mut s = serde::Serializer::serialize_struct_variant(
                    __serializer,
                    "Artifact",
                    3,
                    "ArtifactKind::File",
                    size_of::<ArtifactFile>(),
                )?;
                let x = unsafe { std::ops::Deref::deref(&self.data.file) };
                serde::ser::SerializeStructVariant::serialize_field(
                    &mut s,
                    "ArtifactKind::File",
                    x,
                )?;
                serde::ser::SerializeStructVariant::end(s)
            }
        }
    }
}
impl<'de> serde::Deserialize<'de> for Artifact {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        const VARIANTS: &[&str] = &[
            "ArtifactKind::Hir",
            "ArtifactKind::RestHir",
            "ArtifactKind::JsonRpcHir",
            "ArtifactKind::File",
        ];
        enum __Variant {
            __Case0,
            __Case1,
            __Case2,
            __Case3,
        }
        impl<'de> serde::Deserialize<'de> for __Variant {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where
                D: serde::Deserializer<'de>,
            {
                struct __VariantVisitor;
                impl serde::de::Visitor<'_> for __VariantVisitor {
                    type Value = __Variant;
                    fn expecting(
                        &self,
                        formatter: &mut core::fmt::Formatter,
                    ) -> core::fmt::Result {
                        formatter.write_str("union variant")
                    }
                    fn visit_str<E>(self, value: &str) -> Result<Self::Value, E>
                    where
                        E: serde::de::Error,
                    {
                        match value {
                            "ArtifactKind::Hir" => Ok(__Variant::__Case0),
                            "ArtifactKind::RestHir" => Ok(__Variant::__Case1),
                            "ArtifactKind::JsonRpcHir" => Ok(__Variant::__Case2),
                            "ArtifactKind::File" => Ok(__Variant::__Case3),
                            _ => Err(E::unknown_variant(value, VARIANTS)),
                        }
                    }
                }
                deserializer.deserialize_identifier(__VariantVisitor)
            }
        }
        struct __Visitor;
        impl<'de> serde::de::Visitor<'de> for __Visitor {
            type Value = Artifact;
            fn expecting(
                &self,
                formatter: &mut core::fmt::Formatter,
            ) -> core::fmt::Result {
                formatter.write_str("externally tagged union Artifact")
            }
            fn visit_enum<A>(self, data: A) -> Result<Self::Value, A::Error>
            where
                A: serde::de::EnumAccess<'de>,
            {
                let (variant, variant_access) = data.variant::<__Variant>()?;
                match variant {
                    __Variant::__Case0 => {
                        struct __CaseVisitor;
                        impl<'de> serde::de::Visitor<'de> for __CaseVisitor {
                            type Value = ArtifactHir;
                            fn expecting(
                                &self,
                                formatter: &mut core::fmt::Formatter,
                            ) -> core::fmt::Result {
                                formatter.write_str("struct variant ArtifactKind::Hir")
                            }
                            fn visit_map<M>(
                                self,
                                mut map: M,
                            ) -> Result<Self::Value, M::Error>
                            where
                                M: serde::de::MapAccess<'de>,
                            {
                                let mut value = None;
                                while let Some(key) = map.next_key::<String>()? {
                                    if key == "ArtifactKind::Hir" {
                                        if value.is_some() {
                                            return Err(
                                                serde::de::Error::duplicate_field("ArtifactKind::Hir"),
                                            );
                                        }
                                        value = Some(map.next_value()?);
                                    } else {
                                        let _: serde::de::IgnoredAny = map.next_value()?;
                                    }
                                }
                                value
                                    .ok_or_else(|| {
                                        serde::de::Error::missing_field("ArtifactKind::Hir")
                                    })
                            }
                        }
                        let value = serde::de::VariantAccess::struct_variant(
                            variant_access,
                            &["ArtifactKind::Hir"],
                            __CaseVisitor,
                        )?;
                        let tag = ArtifactKind::Hir;
                        Ok(Artifact {
                            tag,
                            data: ArtifactData {
                                hir: core::mem::ManuallyDrop::new(value),
                            },
                        })
                    }
                    __Variant::__Case1 => {
                        struct __CaseVisitor;
                        impl<'de> serde::de::Visitor<'de> for __CaseVisitor {
                            type Value = ArtifactRestHir;
                            fn expecting(
                                &self,
                                formatter: &mut core::fmt::Formatter,
                            ) -> core::fmt::Result {
                                formatter.write_str("struct variant ArtifactKind::RestHir")
                            }
                            fn visit_map<M>(
                                self,
                                mut map: M,
                            ) -> Result<Self::Value, M::Error>
                            where
                                M: serde::de::MapAccess<'de>,
                            {
                                let mut value = None;
                                while let Some(key) = map.next_key::<String>()? {
                                    if key == "ArtifactKind::RestHir" {
                                        if value.is_some() {
                                            return Err(
                                                serde::de::Error::duplicate_field("ArtifactKind::RestHir"),
                                            );
                                        }
                                        value = Some(map.next_value()?);
                                    } else {
                                        let _: serde::de::IgnoredAny = map.next_value()?;
                                    }
                                }
                                value
                                    .ok_or_else(|| {
                                        serde::de::Error::missing_field("ArtifactKind::RestHir")
                                    })
                            }
                        }
                        let value = serde::de::VariantAccess::struct_variant(
                            variant_access,
                            &["ArtifactKind::RestHir"],
                            __CaseVisitor,
                        )?;
                        let tag = ArtifactKind::RestHir;
                        Ok(Artifact {
                            tag,
                            data: ArtifactData {
                                rest_hir: core::mem::ManuallyDrop::new(value),
                            },
                        })
                    }
                    __Variant::__Case2 => {
                        struct __CaseVisitor;
                        impl<'de> serde::de::Visitor<'de> for __CaseVisitor {
                            type Value = ArtifactJsonRpcHir;
                            fn expecting(
                                &self,
                                formatter: &mut core::fmt::Formatter,
                            ) -> core::fmt::Result {
                                formatter
                                    .write_str("struct variant ArtifactKind::JsonRpcHir")
                            }
                            fn visit_map<M>(
                                self,
                                mut map: M,
                            ) -> Result<Self::Value, M::Error>
                            where
                                M: serde::de::MapAccess<'de>,
                            {
                                let mut value = None;
                                while let Some(key) = map.next_key::<String>()? {
                                    if key == "ArtifactKind::JsonRpcHir" {
                                        if value.is_some() {
                                            return Err(
                                                serde::de::Error::duplicate_field(
                                                    "ArtifactKind::JsonRpcHir",
                                                ),
                                            );
                                        }
                                        value = Some(map.next_value()?);
                                    } else {
                                        let _: serde::de::IgnoredAny = map.next_value()?;
                                    }
                                }
                                value
                                    .ok_or_else(|| {
                                        serde::de::Error::missing_field("ArtifactKind::JsonRpcHir")
                                    })
                            }
                        }
                        let value = serde::de::VariantAccess::struct_variant(
                            variant_access,
                            &["ArtifactKind::JsonRpcHir"],
                            __CaseVisitor,
                        )?;
                        let tag = ArtifactKind::JsonRpcHir;
                        Ok(Artifact {
                            tag,
                            data: ArtifactData {
                                jsonrpc_hir: core::mem::ManuallyDrop::new(value),
                            },
                        })
                    }
                    __Variant::__Case3 => {
                        struct __CaseVisitor;
                        impl<'de> serde::de::Visitor<'de> for __CaseVisitor {
                            type Value = ArtifactFile;
                            fn expecting(
                                &self,
                                formatter: &mut core::fmt::Formatter,
                            ) -> core::fmt::Result {
                                formatter.write_str("struct variant ArtifactKind::File")
                            }
                            fn visit_map<M>(
                                self,
                                mut map: M,
                            ) -> Result<Self::Value, M::Error>
                            where
                                M: serde::de::MapAccess<'de>,
                            {
                                let mut value = None;
                                while let Some(key) = map.next_key::<String>()? {
                                    if key == "ArtifactKind::File" {
                                        if value.is_some() {
                                            return Err(
                                                serde::de::Error::duplicate_field("ArtifactKind::File"),
                                            );
                                        }
                                        value = Some(map.next_value()?);
                                    } else {
                                        let _: serde::de::IgnoredAny = map.next_value()?;
                                    }
                                }
                                value
                                    .ok_or_else(|| {
                                        serde::de::Error::missing_field("ArtifactKind::File")
                                    })
                            }
                        }
                        let value = serde::de::VariantAccess::struct_variant(
                            variant_access,
                            &["ArtifactKind::File"],
                            __CaseVisitor,
                        )?;
                        let tag = ArtifactKind::File;
                        Ok(Artifact {
                            tag,
                            data: ArtifactData {
                                file: core::mem::ManuallyDrop::new(value),
                            },
                        })
                    }
                }
            }
        }
        deserializer.deserialize_enum("Artifact", VARIANTS, __Visitor)
    }
}
