#![allow(unused_variables)]
/// Generated by xidlc 0.8.0 at 2026-03-07 07:36.
#[path = "ipc_artifact.rs"]
mod ipc_artifact;
#[path = "ipc_artifact_deserialize.rs"]
mod ipc_artifact_deserialize;
#[path = "ipc_artifact_serialize.rs"]
mod ipc_artifact_serialize;
#[path = "ipc_codegen.rs"]
mod ipc_codegen;

pub use ipc_artifact::*;
pub use ipc_codegen::*;
