//! Generated by xidlc.
#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unreachable_patterns)]

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::cell::RefCell;
use std::collections::BTreeMap;
use std::ffi::c_void;
use std::io::{BufRead, Write};

pub trait Codegen {
    fn parser_properties(
        &self,
    ) -> Result<::xidl_parser::hir::ParserProperties, xidl_jsonrpc::Error>;

    fn generate(
        &self,
        hir: ::xidl_parser::hir::Specification,
        input: String,
    ) -> Result<Vec<::xidlc::generate::GeneratedFile>, xidl_jsonrpc::Error>;
}

#[derive(Serialize, Deserialize)]
struct CodegenParserPropertiesParams {}

#[derive(Serialize, Deserialize)]
struct CodegenGenerateParams {
    hir: ::xidl_parser::hir::Specification,

    input: String,
}

pub struct CodegenServer<T> {
    inner: T,
}

impl<T> CodegenServer<T> {
    pub fn new(inner: T) -> Self {
        Self { inner }
    }
}

impl<T> xidl_jsonrpc::Handler for CodegenServer<T>
where
    T: Codegen,
{
    fn handle(&self, method: &str, params: Value) -> Result<Value, xidl_jsonrpc::Error> {
        match method {
            "Codegen.parser_properties" => {
                let params: CodegenParserPropertiesParams = serde_json::from_value(params)?;

                let result = self.inner.parser_properties()?;

                Ok(serde_json::to_value(result)?)
            }

            "Codegen.generate" => {
                let params: CodegenGenerateParams = serde_json::from_value(params)?;

                let result = self.inner.generate(params.hir, params.input)?;

                Ok(serde_json::to_value(result)?)
            }

            _ => Err(xidl_jsonrpc::Error::method_not_found(method)),
        }
    }
}

pub struct CodegenClient<R, W> {
    client: RefCell<xidl_jsonrpc::Client<R, W>>,
}

impl<R, W> CodegenClient<R, W>
where
    R: BufRead,
    W: Write,
{
    pub fn new(reader: R, writer: W) -> Self {
        Self {
            client: RefCell::new(xidl_jsonrpc::Client::new(reader, writer)),
        }
    }
}

impl<R, W> Codegen for CodegenClient<R, W>
where
    R: BufRead,
    W: Write,
{
    fn parser_properties(
        &self,
    ) -> Result<::xidl_parser::hir::ParserProperties, xidl_jsonrpc::Error> {
        let params = CodegenParserPropertiesParams {};
        self.client
            .borrow_mut()
            .call("Codegen.parser_properties", params)
    }

    fn generate(
        &self,
        hir: ::xidl_parser::hir::Specification,
        input: String,
    ) -> Result<Vec<::xidlc::generate::GeneratedFile>, xidl_jsonrpc::Error> {
        let params = CodegenGenerateParams { hir, input };
        self.client.borrow_mut().call("Codegen.generate", params)
    }
}
