use std::collections::BTreeMap;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

struct HeaderCase {
    lang: &'static str,
    fixture: &'static str,
    comment_prefix: &'static str,
}

fn fixture_path(relative: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join(relative)
}

fn current_xidlc_version() -> &'static str {
    option_env!("XIDLC_VERSION").unwrap_or(env!("CARGO_PKG_VERSION"))
}

fn current_git_hash() -> String {
    option_env!("XIDLC_GIT_HASH")
        .filter(|hash| !hash.trim().is_empty())
        .unwrap_or("unknown")
        .to_string()
}

fn expected_banner(comment_prefix: &str) -> String {
    format!(
        "{comment_prefix} Code generated by xidlc-v{}-{}. DO NOT EDIT.",
        current_xidlc_version(),
        current_git_hash()
    )
}

fn merge_generated_files(files: Vec<xidlc::driver::File>) -> BTreeMap<String, String> {
    let mut merged: BTreeMap<String, String> = BTreeMap::new();
    for file in files {
        merged
            .entry(file.path().to_string())
            .and_modify(|content| content.push_str(file.content()))
            .or_insert_with(|| file.content().to_string());
    }
    merged
}

#[tokio::test(flavor = "current_thread")]
async fn generated_headers_include_current_version_and_git_hash_for_code_targets() {
    let cases = [
        HeaderCase {
            lang: "rust",
            fixture: "shared/basic.idl",
            comment_prefix: "//",
        },
        HeaderCase {
            lang: "rust-jsonrpc",
            fixture: "openrpc/simple.idl",
            comment_prefix: "//",
        },
        HeaderCase {
            lang: "axum",
            fixture: "shared/http_defaults.idl",
            comment_prefix: "//",
        },
        HeaderCase {
            lang: "go",
            fixture: "shared/basic.idl",
            comment_prefix: "//",
        },
        HeaderCase {
            lang: "go-rest",
            fixture: "shared/http_defaults.idl",
            comment_prefix: "//",
        },
        HeaderCase {
            lang: "ts",
            fixture: "shared/basic.idl",
            comment_prefix: "//",
        },
        HeaderCase {
            lang: "typescript-rest",
            fixture: "shared/http_defaults.idl",
            comment_prefix: "//",
        },
        HeaderCase {
            lang: "python",
            fixture: "shared/basic.idl",
            comment_prefix: "#",
        },
        HeaderCase {
            lang: "python-rest",
            fixture: "shared/http_defaults.idl",
            comment_prefix: "#",
        },
    ];

    for case in cases {
        let path = fixture_path(case.fixture);
        let source = fs::read_to_string(&path).expect("read fixture");
        let mut generator = xidlc::driver::Generator::new(case.lang.to_string());
        let files = generator
            .generate_from_idl(&source, &path, HashMap::new())
            .await
            .expect("generate files");
        assert!(
            !files.is_empty(),
            "{} should generate at least one file",
            case.lang
        );

        let expected = expected_banner(case.comment_prefix);
        for (path, content) in merge_generated_files(files) {
            assert!(
                content.starts_with(&expected),
                "{} {} missing generated header, first line: {:?}",
                case.lang,
                path,
                content.lines().next()
            );
            assert_eq!(
                content.matches("Code generated by xidlc-v").count(),
                1,
                "{} {} should contain exactly one generated header",
                case.lang,
                path
            );
        }
    }
}
