// Code generated by xidlc-v0.0.1-snapshot. DO NOT EDIT.

package hello_world

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/gin-gonic/gin"
	xidlgohttp "github.com/xidl/xidl/golang/xidl-go-rest"
)

var (
	_ = bytes.Buffer{}
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strings.TrimSpace
)

type HelloWorldService interface {
	SayHello(ctx context.Context, req *HelloWorldSayHelloRequest) (*HelloWorldSayHelloResponse, error)
	Trusted(ctx context.Context, req *HelloWorldTrustedRequest) (*HelloWorldTrustedResponse, error)
}

func RegisterHelloWorldHandler(r gin.IRouter, svc HelloWorldService) {
	r.OPTIONS("/hello", xidlgohttp.CORSMiddleware([]string{"*"}))
	r.POST("/hello", xidlgohttp.CORSMiddleware([]string{"*"}), func(c *gin.Context) {
		if err := xidlgohttp.GinRequireAccept(c, ""); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusNotAcceptable, http.StatusNotAcceptable, err.Error())
			return
		}
		if err := xidlgohttp.GinRequireContentType(c, "text/plain"); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusUnsupportedMediaType, http.StatusUnsupportedMediaType, err.Error())
			return
		}

		req := &HelloWorldSayHelloRequest{}
		var body string
		if err := xidlgohttp.GinDecodeBody(c, "text/plain", &body); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusBadRequest, http.StatusBadRequest, err.Error())
			return
		}
		req.Name = body
		if _, err := svc.SayHello(c.Request.Context(), req); err != nil {
			if httpErr, ok := err.(*xidlgohttp.HttpError); ok {
				xidlgohttp.GinWriteJSONError(c, httpErr.Status, httpErr.Code, httpErr.Message)
			} else {
				xidlgohttp.GinWriteJSONError(c, http.StatusInternalServerError, http.StatusInternalServerError, err.Error())
			}
			return
		}
		c.Status(http.StatusNoContent)
	})
	r.OPTIONS("/trusted", xidlgohttp.CORSMiddleware([]string{"http://trust.me"}))
	r.GET("/trusted", xidlgohttp.CORSMiddleware([]string{"http://trust.me"}), func(c *gin.Context) {
		if err := xidlgohttp.GinRequireAccept(c, ""); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusNotAcceptable, http.StatusNotAcceptable, err.Error())
			return
		}
		if err := xidlgohttp.GinRequireContentType(c, ""); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusUnsupportedMediaType, http.StatusUnsupportedMediaType, err.Error())
			return
		}

		req := &HelloWorldTrustedRequest{}
		if _, err := svc.Trusted(c.Request.Context(), req); err != nil {
			if httpErr, ok := err.(*xidlgohttp.HttpError); ok {
				xidlgohttp.GinWriteJSONError(c, httpErr.Status, httpErr.Code, httpErr.Message)
			} else {
				xidlgohttp.GinWriteJSONError(c, http.StatusInternalServerError, http.StatusInternalServerError, err.Error())
			}
			return
		}
		c.Status(http.StatusNoContent)
	})
}

type HelloWorldClient struct {
	baseURL    string
	httpClient *http.Client
	auth       xidlgohttp.ClientAuth
}

func NewHelloWorldClient(baseURL string, httpClient *http.Client, auth xidlgohttp.ClientAuth) *HelloWorldClient {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &HelloWorldClient{baseURL: strings.TrimRight(baseURL, "/"), httpClient: httpClient, auth: auth}
}

func (c *HelloWorldClient) SayHello(ctx context.Context, req *HelloWorldSayHelloRequest) (*HelloWorldSayHelloResponse, error) {
	requestURL := c.baseURL + formatHelloWorldSayHelloPath(req)
	body := req.Name
	var requestBody bytes.Buffer
	if err := xidlgohttp.MustCodecForMime("text/plain").Encode(&requestBody, body); err != nil {
		return nil, err
	}
	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, &requestBody)
	if err != nil {
		return nil, err
	}
	httpReq.Header.Set("Content-Type", "text/plain")
	httpReq.Header.Set("Accept", "")
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("http %d", resp.StatusCode)
	}
	decoded, err := decodeHelloWorldSayHelloResponse(resp)
	if err != nil {
		return nil, err
	}
	return &decoded, nil
}

func (c *HelloWorldClient) Trusted(ctx context.Context, req *HelloWorldTrustedRequest) (*HelloWorldTrustedResponse, error) {
	requestURL := c.baseURL + formatHelloWorldTrustedPath(req)
	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, err
	}
	httpReq.Header.Set("Accept", "")
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("http %d", resp.StatusCode)
	}
	decoded, err := decodeHelloWorldTrustedResponse(resp)
	if err != nil {
		return nil, err
	}
	return &decoded, nil
}

type HelloWorldSayHelloRequest struct {
	Name string `xjson:"name" form:"name"`
}

type HelloWorldSayHelloResponse struct {
}

func HelloWorldSayHelloSecurityRequirements() []xidlgohttp.SecurityRequirement {
	return []xidlgohttp.SecurityRequirement{}
}

func HelloWorldSayHelloDeprecated() xidlgohttp.DeprecatedInfo {
	return xidlgohttp.DeprecatedInfo{
		Deprecated: false,
	}
}

func formatHelloWorldSayHelloPath(req *HelloWorldSayHelloRequest) string {
	path := "/hello"
	return path
}
func decodeHelloWorldSayHelloResponse(resp *http.Response) (HelloWorldSayHelloResponse, error) {
	out := HelloWorldSayHelloResponse{}
	return out, nil
}

type HelloWorldTrustedRequest struct {
}

type HelloWorldTrustedResponse struct {
}

func HelloWorldTrustedSecurityRequirements() []xidlgohttp.SecurityRequirement {
	return []xidlgohttp.SecurityRequirement{}
}

func HelloWorldTrustedDeprecated() xidlgohttp.DeprecatedInfo {
	return xidlgohttp.DeprecatedInfo{
		Deprecated: false,
	}
}

func formatHelloWorldTrustedPath(req *HelloWorldTrustedRequest) string {
	path := "/trusted"
	return path
}
func decodeHelloWorldTrustedResponse(resp *http.Response) (HelloWorldTrustedResponse, error) {
	out := HelloWorldTrustedResponse{}
	return out, nil
}
