// Code generated by xidlc. DO NOT EDIT.

package hello_world

import (
	"bytes"
	"context"
	"fmt"
	xidlgohttp "github.com/xidl/xidl/golang/xidl-go-http"
	"net/http"
	"net/url"
	"strings"
)

var (
	_ = bytes.Buffer{}
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strings.TrimSpace
)

type HelloWorldService interface {
	SayHello(ctx context.Context, req *HelloWorldSayHelloRequest) (*HelloWorldSayHelloResponse, error)
}

func NewHelloWorldHandler(svc HelloWorldService) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("POST /hello", func(w http.ResponseWriter, r *http.Request) {
		if err := xidlgohttp.RequireAccept(r, "application/json"); err != nil {
			xidlgohttp.WriteJSONError(w, http.StatusNotAcceptable, "NOT_ACCEPTABLE", err.Error())
			return
		}
		if err := xidlgohttp.RequireContentType(r, "application/json"); err != nil {
			xidlgohttp.WriteJSONError(w, http.StatusUnsupportedMediaType, "UNSUPPORTED_MEDIA_TYPE", err.Error())
			return
		}

		req := &HelloWorldSayHelloRequest{}
		body := HelloWorldSayHelloRequestBody{}
		if err := xidlgohttp.DecodeBody(r, "application/json", &body); err != nil {
			xidlgohttp.WriteJSONError(w, http.StatusBadRequest, "BAD_REQUEST", err.Error())
			return
		}
		req.Name = body.Name
		if _, err := svc.SayHello(r.Context(), req); err != nil {
			xidlgohttp.WriteJSONError(w, http.StatusInternalServerError, "INTERNAL", err.Error())
			return
		}
		w.WriteHeader(http.StatusNoContent)
	})
	return mux
}

type HelloWorldClient struct {
	baseURL    string
	httpClient *http.Client
	auth       xidlgohttp.ClientAuth
}

func NewHelloWorldClient(baseURL string, httpClient *http.Client, auth xidlgohttp.ClientAuth) *HelloWorldClient {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &HelloWorldClient{baseURL: strings.TrimRight(baseURL, "/"), httpClient: httpClient, auth: auth}
}

func (c *HelloWorldClient) SayHello(ctx context.Context, req *HelloWorldSayHelloRequest) (*HelloWorldSayHelloResponse, error) {
	requestURL := c.baseURL + formatHelloWorldSayHelloPath(req)
	body := HelloWorldSayHelloRequestBody{
		Name: req.Name,
	}
	var requestBody bytes.Buffer
	if err := xidlgohttp.MustCodecForMime("application/json").Encode(&requestBody, body); err != nil {
		return nil, err
	}
	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, &requestBody)
	if err != nil {
		return nil, err
	}
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("Accept", "application/json")
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("http %d", resp.StatusCode)
	}
	decoded, err := decodeHelloWorldSayHelloResponse(resp)
	if err != nil {
		return nil, err
	}
	return &decoded, nil
}

type HelloWorldSayHelloRequest struct {
	Name string `json:"name" form:"name"`
}

type HelloWorldSayHelloRequestBody struct {
	Name string `json:"name" form:"name"`
}

type HelloWorldSayHelloResponse struct {
}

func HelloWorldSayHelloSecurityRequirements() []xidlgohttp.SecurityRequirement {
	return []xidlgohttp.SecurityRequirement{}
}

func HelloWorldSayHelloDeprecated() xidlgohttp.DeprecatedInfo {
	return xidlgohttp.DeprecatedInfo{
		Deprecated: false,
	}
}

func formatHelloWorldSayHelloPath(req *HelloWorldSayHelloRequest) string {
	path := "/hello"
	return path
}
func decodeHelloWorldSayHelloResponse(resp *http.Response) (HelloWorldSayHelloResponse, error) {
	out := HelloWorldSayHelloResponse{}
	return out, nil
}
