//! Axum-based runtime support for code generated by `xidlc`.
//!
//! This crate provides the shared request/response, client, server, auth, and
//! streaming helpers used by generated HTTP and WebSocket services.
//!
//! Generated code typically depends on a small subset of these APIs directly:
//! [`Client`] for outbound calls, [`Server`] and [`Service`] for serving Axum
//! routers, [`Request`] for preserving request headers alongside decoded input,
//! and the [`stream`] module for SSE, NDJSON, and bidirectional WebSocket
//! transport.

//! Choose `router` without default features to mount generated HTTP routes in
//! an existing host, including WebAssembly hosts. `server` adds native TCP
//! serving and connection upgrades. `stream` remains a separate capability;
//! its WebSocket dependencies require native networking.

mod error;
/// Error and result types used throughout the runtime.
pub use error::{Error, ErrorBody, Result};

#[cfg(feature = "client")]
mod client;
#[cfg(feature = "client")]
/// Client-side HTTP helpers and auth application utilities.
pub use client::{Client, ClientAuthRequirement};

#[cfg(feature = "server")]
mod server;
#[cfg(feature = "server")]
/// Server-side builder for listening on native HTTP connections.
pub use server::Server;

#[cfg(feature = "router")]
mod service;
#[cfg(feature = "router")]
/// Trait for mounting generated services in an Axum router.
pub use service::Service;

mod request;
/// Request wrapper preserving headers alongside decoded payload data.
pub use request::Request;

/// HTTP content negotiation and serde-related helpers.
pub mod http;
mod serde_factory;
/// MIME-aware serialization and deserialization helpers.
pub use serde_factory::{DeserializeFactory, SerializeFactory};
/// SSE, NDJSON, and WebSocket streaming primitives.
#[cfg(feature = "stream")]
pub mod stream;

/// Authentication helpers shared by generated handlers and clients.
pub mod auth;
/// Credentials shared by generated clients and authenticated handlers.
pub use auth::ClientAuth;
/// API key auth types, available without the `client` feature for server use.
pub use auth::api_key::{ApiKeyAuth, ApiKeyAuthError, ApiKeyLocation, extract_api_key};

#[cfg(feature = "server")]
/// HTTP connection upgrade helpers.
pub mod upgrade;

#[cfg(feature = "router")]
/// Re-export of `axum` so generated code can depend on a single runtime crate.
pub use axum;
#[cfg(feature = "router")]
/// Re-export of `axum-extra` for typed header support.
pub use axum_extra;
/// Cookie encoding shared by generated HTTP clients and servers.
pub use cookie;
/// Re-export of `futures-util` for generated stream code.
pub use futures_util;
#[cfg(feature = "client")]
/// Re-export of `reqwest` for generated client code.
pub use reqwest;
/// Re-export of `serde` for generated request/response models.
pub use serde;
/// Re-export of `serde_json` for generated JSON handling.
pub use serde_json;
/// Re-export of `serde_urlencoded` for generated form handling.
pub use serde_urlencoded;
#[cfg(any(feature = "server", feature = "stream"))]
/// Re-export of `tokio` for generated async runtime integration.
pub use tokio;
/// Re-export of `tokio-tungstenite` for generated WebSocket clients.
#[cfg(feature = "stream")]
pub use tokio_tungstenite;
#[cfg(feature = "router")]
/// Re-export of `tower-http` for generated middleware wiring.
pub use tower_http;
