#pragma xidlc package xidlc
#pragma xidlc version v1.0.0

@http_bearer
interface HttpSecurityStreamService {
    @server_stream
    @stream_codec("sse")
    @get(path = "/channels/{channel}/events")
    string watch_channel(@path @rename("channel") string channel);

    @no_security
    @server_stream
    @stream_codec("sse")
    @get(path = "/channels/public/events")
    string watch_public();
};
