interface HttpStreamSseService {
    @server_stream
    @stream_codec("sse")
    @path("/events/{topic}{?lang}")
    string watch_topic(
        @path @rename("topic")
        string topic,
        @query @rename("lang")
        string lang
    );
    @server_stream
    attribute boolean online;
};
