//! Axum-based runtime support for code generated by `xidlc`.
//!
//! This crate provides the shared request/response, client, server, auth, and
//! streaming helpers used by generated HTTP and WebSocket services.
//!
//! Generated code typically depends on a small subset of these APIs directly:
//! [`Client`] for outbound calls, [`Server`] and [`Service`] for serving Axum
//! routers, [`Request`] for preserving request headers alongside decoded input,
//! and the [`stream`] module for SSE, NDJSON, and bidirectional WebSocket
//! transport.

mod error;
/// Error and result types used throughout the runtime.
pub use error::{Error, ErrorBody, Result};

#[cfg(feature = "client")]
mod client;
#[cfg(feature = "client")]
/// Client-side HTTP helpers and auth application utilities.
pub use client::{ApiKeyAuth, Client, ClientApiKeyLocation, ClientAuth, ClientAuthRequirement};

mod server;
/// Server-side traits and builders for mounting generated services.
pub use server::{Server, Service};

mod request;
/// Request wrapper preserving headers alongside decoded payload data.
pub use request::Request;

/// HTTP content negotiation and serde-related helpers.
pub mod http;
mod serde_factory;
/// MIME-aware serialization and deserialization helpers.
pub use serde_factory::{DeserializeFactory, SerializeFactory};
/// SSE, NDJSON, and WebSocket streaming primitives.
#[cfg(feature = "stream")]
pub mod stream;

/// Authentication helpers shared by generated handlers and clients.
pub mod auth;

/// Re-export of `axum` so generated code can depend on a single runtime crate.
pub use axum;
/// Re-export of `axum-extra` for typed header support.
pub use axum_extra;
/// Re-export of `futures-util` for generated stream code.
pub use futures_util;
#[cfg(feature = "client")]
/// Re-export of `reqwest` for generated client code.
pub use reqwest;
/// Re-export of `serde` for generated request/response models.
pub use serde;
/// Re-export of `serde_json` for generated JSON handling.
pub use serde_json;
/// Re-export of `serde_urlencoded` for generated form handling.
pub use serde_urlencoded;
/// Re-export of `tokio` for generated async runtime integration.
pub use tokio;
/// Re-export of `tokio-tungstenite` for generated WebSocket clients.
#[cfg(feature = "stream")]
pub use tokio_tungstenite;
