use serde::Serialize;

#[derive(Serialize)]
pub struct MethodContext {
    pub name: String,
    pub raw_name: String,
    pub rust_attrs: Vec<String>,
    pub deprecated: bool,
    pub deprecated_since: Option<String>,
    pub deprecated_after: Option<String>,
    pub deprecated_note: Option<String>,
    pub params: Vec<String>,
    pub param_names: Vec<String>,
    pub server_params: Vec<String>,
    pub server_param_names: Vec<String>,
    pub ret: String,
    pub response_ty: String,
    pub request_body_flatten: bool,
    pub http_method: String,
    pub http_method_fn: String,
    pub reqwest_method: String,
    pub path: String,
    pub paths: Vec<String>,
    pub struct_prefix: String,
    pub path_params: Vec<ParamContext>,
    pub query_params: Vec<ParamContext>,
    pub header_params: Vec<ParamContext>,
    pub cookie_params: Vec<ParamContext>,
    pub body_params: Vec<ParamContext>,
    pub request_ty: String,
    pub request_payload_ty: String,
    pub request_struct: Option<String>,
    pub auth_wrapper_struct: Option<String>,
    pub auth_in_request_struct: bool,
    pub has_basic_auth: bool,
    pub has_bearer_auth: bool,
    pub api_key_requirements: Vec<ApiKeyContext>,
    pub auth_source_interface: bool,
    pub auth_source_method: bool,
    pub auth_param: Option<String>,
    pub auth_param_ty: String,
    pub auth_ty: String,
    pub basic_auth_realm: String,
    pub request_params: Vec<ParamContext>,
    pub response_struct: Option<String>,
    pub response_params: Vec<ParamContext>,
    pub response_body_params: Vec<ParamContext>,
    pub response_header_params: Vec<ParamContext>,
    pub response_cookie_params: Vec<ParamContext>,
    pub response_include_return: bool,
    pub response_is_empty: bool,
    pub return_is_unit: bool,
    pub is_server_stream: bool,
    pub is_client_stream: bool,
    pub is_bidi_stream: bool,
    pub request_item_ty: String,
    pub ret_in_ty: String,
    pub ret_out_ty: String,
    pub ret_in_expr: String,
    pub ret_out_expr: String,
    pub request_content_type: String,
    pub response_content_type: String,
}

#[derive(Serialize, Clone)]
pub struct ParamContext {
    pub name: String,
    pub raw_name: String,
    pub wire_name: String,
    pub path_template_name: String,
    pub ty: String,
    pub in_ty: String,
    pub out_ty: String,
    pub source: String,
    pub serde_rename: Option<String>,
    pub header_is_multi: bool,
    pub header_item_ty: String,
    pub header_item_is_string: bool,
    pub header_item_is_primitive: bool,
    pub cookie_is_multi: bool,
    pub cookie_item_ty: String,
    pub cookie_item_is_string: bool,
    pub cookie_item_is_primitive: bool,
    pub optional: bool,
    pub inner_ty: String,
    pub flatten: bool,
    pub in_expr: String,
    pub out_expr: String,
    pub field_in_expr: String,
    pub field_out_expr: String,
}

#[derive(Serialize, Clone)]
pub struct ApiKeyContext {
    pub location: String,
    pub name: String,
}

pub struct DeprecatedContext {
    pub deprecated: bool,
    pub since: Option<String>,
    pub after: Option<String>,
    pub note: Option<String>,
}
