// Code generated by xidlc. DO NOT EDIT.

package http_security

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	xidlgohttp "github.com/xidl/xidl/golang/xidl-go-http"
)

var (
	_ = bytes.Buffer{}
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strings.TrimSpace
)

type HttpSecurityApiService interface {
	GetReport(ctx context.Context, req *HttpSecurityApiGetReportRequest) (*HttpSecurityApiGetReportResponse, error)
	UpdateReport(ctx context.Context, req *HttpSecurityApiUpdateReportRequest) (*HttpSecurityApiUpdateReportResponse, error)
	Health(ctx context.Context, req *HttpSecurityApiHealthRequest) (*HttpSecurityApiHealthResponse, error)
}

func NewHttpSecurityApiHandler(svc HttpSecurityApiService) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /reports/{id}", func(w http.ResponseWriter, r *http.Request) {
		if err := xidlgohttp.RequireAccept(r, "application/json"); err != nil {
			xidlgohttp.WriteJSONError(w, http.StatusNotAcceptable, "NOT_ACCEPTABLE", err.Error())
			return
		}
		ctx, err := xidlgohttp.RequireAuth(r, HttpSecurityApiGetReportSecurityRequirements())
		if err != nil {
			xidlgohttp.Unauthorized(w, HttpSecurityApiGetReportSecurityRequirements())
			return
		}
		r = r.WithContext(ctx)

	req := &HttpSecurityApiGetReportRequest{}

 	if value, err := xidlgohttp.PathString(r, "id"); err == nil { req.Id = value } else {
 		xidlgohttp.WriteJSONError(w, http.StatusBadRequest, "BAD_REQUEST", err.Error())
 		return
 	}

 	if value, err := xidlgohttp.HeaderString(r.Header, "X-Trace-Id"); err == nil { req.TraceId = value } else {
 		xidlgohttp.WriteJSONError(w, http.StatusBadRequest, "BAD_REQUEST", err.Error())
 		return
 	}
		resp, err := svc.GetReport(r.Context(), req)
		if err != nil {
			xidlgohttp.WriteJSONError(w, http.StatusInternalServerError, "INTERNAL", err.Error())
			return
		}

	if err := xidlgohttp.EncodeBody(w, "application/json", resp.Return); err != nil {
		xidlgohttp.WriteJSONError(w, http.StatusInternalServerError, "ENCODE", err.Error())
	}
	})
	mux.HandleFunc("POST /reports/{id}", func(w http.ResponseWriter, r *http.Request) {
		if err := xidlgohttp.RequireAccept(r, "application/json"); err != nil {
			xidlgohttp.WriteJSONError(w, http.StatusNotAcceptable, "NOT_ACCEPTABLE", err.Error())
			return
		}
		ctx, err := xidlgohttp.RequireAuth(r, HttpSecurityApiUpdateReportSecurityRequirements())
		if err != nil {
			xidlgohttp.Unauthorized(w, HttpSecurityApiUpdateReportSecurityRequirements())
			return
		}
		r = r.WithContext(ctx)
		if err := xidlgohttp.RequireContentType(r, "application/json"); err != nil {
			xidlgohttp.WriteJSONError(w, http.StatusUnsupportedMediaType, "UNSUPPORTED_MEDIA_TYPE", err.Error())
			return
		}

	req := &HttpSecurityApiUpdateReportRequest{}

 	if value, err := xidlgohttp.PathString(r, "id"); err == nil { req.Id = value } else {
 		xidlgohttp.WriteJSONError(w, http.StatusBadRequest, "BAD_REQUEST", err.Error())
 		return
 	}
	body := HttpSecurityApiUpdateReportRequestBody{}
	if err := xidlgohttp.DecodeBody(r, "application/json", &body); err != nil {
		xidlgohttp.WriteJSONError(w, http.StatusBadRequest, "BAD_REQUEST", err.Error())
		return
	}
	req.Body = body.Body
		resp, err := svc.UpdateReport(r.Context(), req)
		if err != nil {
			xidlgohttp.WriteJSONError(w, http.StatusInternalServerError, "INTERNAL", err.Error())
			return
		}

	if err := xidlgohttp.EncodeBody(w, "application/json", resp.Return); err != nil {
		xidlgohttp.WriteJSONError(w, http.StatusInternalServerError, "ENCODE", err.Error())
	}
	})
	mux.HandleFunc("GET /health", func(w http.ResponseWriter, r *http.Request) {
		if err := xidlgohttp.RequireAccept(r, "application/json"); err != nil {
			xidlgohttp.WriteJSONError(w, http.StatusNotAcceptable, "NOT_ACCEPTABLE", err.Error())
			return
		}

	req := &HttpSecurityApiHealthRequest{}
		resp, err := svc.Health(r.Context(), req)
		if err != nil {
			xidlgohttp.WriteJSONError(w, http.StatusInternalServerError, "INTERNAL", err.Error())
			return
		}

	if err := xidlgohttp.EncodeBody(w, "application/json", resp.Return); err != nil {
		xidlgohttp.WriteJSONError(w, http.StatusInternalServerError, "ENCODE", err.Error())
	}
	})
	return mux
}

type HttpSecurityApiClient struct {
	baseURL string
	httpClient *http.Client
	auth xidlgohttp.ClientAuth
}

func NewHttpSecurityApiClient(baseURL string, httpClient *http.Client, auth xidlgohttp.ClientAuth) *HttpSecurityApiClient {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &HttpSecurityApiClient{baseURL: strings.TrimRight(baseURL, "/"), httpClient: httpClient, auth: auth}
}

func (c *HttpSecurityApiClient) GetReport(ctx context.Context, req *HttpSecurityApiGetReportRequest) (*HttpSecurityApiGetReportResponse, error) {
	requestURL := c.baseURL + formatHttpSecurityApiGetReportPath(req)
	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil { return nil, err }
	httpReq.Header.Set("Accept", "application/json")

 	httpReq.Header.Set("X-Trace-Id", req.TraceId)
	xidlgohttp.ApplyClientAuth(httpReq, c.auth, HttpSecurityApiGetReportSecurityRequirements())
	resp, err := c.httpClient.Do(httpReq)
	if err != nil { return nil, err }
	defer resp.Body.Close()
	if resp.StatusCode >= 400 { return nil, fmt.Errorf("http %d", resp.StatusCode) }
	decoded, err := decodeHttpSecurityApiGetReportResponse(resp)
	if err != nil { return nil, err }
	return &decoded, nil
}

func (c *HttpSecurityApiClient) UpdateReport(ctx context.Context, req *HttpSecurityApiUpdateReportRequest) (*HttpSecurityApiUpdateReportResponse, error) {
	requestURL := c.baseURL + formatHttpSecurityApiUpdateReportPath(req)
	body := HttpSecurityApiUpdateReportRequestBody{
		Body: req.Body,
	}
	var requestBody bytes.Buffer
	if err := xidlgohttp.MustCodecForMime("application/json").Encode(&requestBody, body); err != nil { return nil, err }
	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, &requestBody)
	if err != nil { return nil, err }
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("Accept", "application/json")
	xidlgohttp.ApplyClientAuth(httpReq, c.auth, HttpSecurityApiUpdateReportSecurityRequirements())
	resp, err := c.httpClient.Do(httpReq)
	if err != nil { return nil, err }
	defer resp.Body.Close()
	if resp.StatusCode >= 400 { return nil, fmt.Errorf("http %d", resp.StatusCode) }
	decoded, err := decodeHttpSecurityApiUpdateReportResponse(resp)
	if err != nil { return nil, err }
	return &decoded, nil
}

func (c *HttpSecurityApiClient) Health(ctx context.Context, req *HttpSecurityApiHealthRequest) (*HttpSecurityApiHealthResponse, error) {
	requestURL := c.baseURL + formatHttpSecurityApiHealthPath(req)
	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil { return nil, err }
	httpReq.Header.Set("Accept", "application/json")
	resp, err := c.httpClient.Do(httpReq)
	if err != nil { return nil, err }
	defer resp.Body.Close()
	if resp.StatusCode >= 400 { return nil, fmt.Errorf("http %d", resp.StatusCode) }
	decoded, err := decodeHttpSecurityApiHealthResponse(resp)
	if err != nil { return nil, err }
	return &decoded, nil
}

type HttpSecurityApiGetReportRequest struct {
	Id string `json:"id" form:"id"`
	TraceId string `json:"trace_id" form:"trace_id"`
}

type HttpSecurityApiGetReportResponse struct {
	Return string `json:"return"`
}

func HttpSecurityApiGetReportSecurityRequirements() []xidlgohttp.SecurityRequirement {
	return []xidlgohttp.SecurityRequirement{
		{Kind: xidlgohttp.SecurityBasic, Realm: "GetReport"},
		{Kind: xidlgohttp.SecurityAPIKey, Location: xidlgohttp.ApiKeyHeader, Name: "X-Org-Key"},
	}
}

func HttpSecurityApiGetReportDeprecated() xidlgohttp.DeprecatedInfo {
	return xidlgohttp.DeprecatedInfo{
		Deprecated: false,
	}
}

func formatHttpSecurityApiGetReportPath(req *HttpSecurityApiGetReportRequest) string {
	path := "/reports/{id}"
	path = strings.ReplaceAll(path, "{id}", req.Id)
	path = strings.ReplaceAll(path, "{*id}", req.Id)
	return path
}
func decodeHttpSecurityApiGetReportResponse(resp *http.Response) (HttpSecurityApiGetReportResponse, error) {
	out := HttpSecurityApiGetReportResponse{}
	var body string
	if err := xidlgohttp.MustCodecForMime("application/json").Decode(resp.Body, &body); err != nil { return out, err }
	out.Return = body
	return out, nil
}
type HttpSecurityApiUpdateReportRequest struct {
	Id string `json:"id" form:"id"`
	Body string `json:"body" form:"body"`
}

type HttpSecurityApiUpdateReportRequestBody struct {
	Body string `json:"body" form:"body"`
}

type HttpSecurityApiUpdateReportResponse struct {
	Return string `json:"return"`
}

func HttpSecurityApiUpdateReportSecurityRequirements() []xidlgohttp.SecurityRequirement {
	return []xidlgohttp.SecurityRequirement{
		{Kind: xidlgohttp.SecurityOAuth2, Scopes: []string{"reports:write"}},
	}
}

func HttpSecurityApiUpdateReportDeprecated() xidlgohttp.DeprecatedInfo {
	return xidlgohttp.DeprecatedInfo{
		Deprecated: false,
	}
}

func formatHttpSecurityApiUpdateReportPath(req *HttpSecurityApiUpdateReportRequest) string {
	path := "/reports/{id}"
	path = strings.ReplaceAll(path, "{id}", req.Id)
	path = strings.ReplaceAll(path, "{*id}", req.Id)
	return path
}
func decodeHttpSecurityApiUpdateReportResponse(resp *http.Response) (HttpSecurityApiUpdateReportResponse, error) {
	out := HttpSecurityApiUpdateReportResponse{}
	var body string
	if err := xidlgohttp.MustCodecForMime("application/json").Decode(resp.Body, &body); err != nil { return out, err }
	out.Return = body
	return out, nil
}
type HttpSecurityApiHealthRequest struct {
}

type HttpSecurityApiHealthResponse struct {
	Return string `json:"return"`
}

func HttpSecurityApiHealthSecurityRequirements() []xidlgohttp.SecurityRequirement {
	return []xidlgohttp.SecurityRequirement{
	}
}

func HttpSecurityApiHealthDeprecated() xidlgohttp.DeprecatedInfo {
	return xidlgohttp.DeprecatedInfo{
		Deprecated: false,
	}
}

func formatHttpSecurityApiHealthPath(req *HttpSecurityApiHealthRequest) string {
	path := "/health"
	return path
}
func decodeHttpSecurityApiHealthResponse(resp *http.Response) (HttpSecurityApiHealthResponse, error) {
	out := HttpSecurityApiHealthResponse{}
	var body string
	if err := xidlgohttp.MustCodecForMime("application/json").Decode(resp.Body, &body); err != nil { return out, err }
	out.Return = body
	return out, nil
}
