// Code generated by xidlc-v0.0.1-snapshot. DO NOT EDIT.

package http_security

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/gin-gonic/gin"
	xidlgohttp "github.com/xidl/xidl/golang/xidl-go-rest"
)

var (
	_ = bytes.Buffer{}
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strings.TrimSpace
)

type HttpSecurityApiService interface {
	GetReport(ctx context.Context, req *HttpSecurityApiGetReportRequest) (*HttpSecurityApiGetReportResponse, error)
	UpdateReport(ctx context.Context, req *HttpSecurityApiUpdateReportRequest) (*HttpSecurityApiUpdateReportResponse, error)
	Health(ctx context.Context, req *HttpSecurityApiHealthRequest) (*HttpSecurityApiHealthResponse, error)
}

func RegisterHttpSecurityApiHandler(r gin.IRouter, svc HttpSecurityApiService) {
	r.GET("/reports/:id", func(c *gin.Context) {
		if err := xidlgohttp.GinRequireAccept(c, "application/json"); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusNotAcceptable, "NOT_ACCEPTABLE", err.Error())
			return
		}
		ctx, err := xidlgohttp.RequireAuth(c.Request, HttpSecurityApiGetReportSecurityRequirements())
		if err != nil {
			xidlgohttp.Unauthorized(c.Writer, HttpSecurityApiGetReportSecurityRequirements())
			return
		}
		c.Request = c.Request.WithContext(ctx)

		req := &HttpSecurityApiGetReportRequest{}

		if value, err := xidlgohttp.GinPathString(c, "id"); err == nil {
			req.Id = value
		} else {
			xidlgohttp.GinWriteJSONError(c, http.StatusBadRequest, "BAD_REQUEST", err.Error())
			return
		}

		if value, err := xidlgohttp.HeaderString(c.Request.Header, "X-Trace-Id"); err == nil {
			req.TraceId = value
		} else {
			xidlgohttp.GinWriteJSONError(c, http.StatusBadRequest, "BAD_REQUEST", err.Error())
			return
		}
		resp, err := svc.GetReport(c.Request.Context(), req)
		if err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusInternalServerError, "INTERNAL", err.Error())
			return
		}

		if err := xidlgohttp.GinEncodeBody(c, "application/json", resp.Return); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusInternalServerError, "ENCODE", err.Error())
		}
	})
	r.POST("/reports/:id", func(c *gin.Context) {
		if err := xidlgohttp.GinRequireAccept(c, "application/json"); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusNotAcceptable, "NOT_ACCEPTABLE", err.Error())
			return
		}
		ctx, err := xidlgohttp.RequireAuth(c.Request, HttpSecurityApiUpdateReportSecurityRequirements())
		if err != nil {
			xidlgohttp.Unauthorized(c.Writer, HttpSecurityApiUpdateReportSecurityRequirements())
			return
		}
		c.Request = c.Request.WithContext(ctx)
		if err := xidlgohttp.GinRequireContentType(c, "application/json"); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusUnsupportedMediaType, "UNSUPPORTED_MEDIA_TYPE", err.Error())
			return
		}

		req := &HttpSecurityApiUpdateReportRequest{}

		if value, err := xidlgohttp.GinPathString(c, "id"); err == nil {
			req.Id = value
		} else {
			xidlgohttp.GinWriteJSONError(c, http.StatusBadRequest, "BAD_REQUEST", err.Error())
			return
		}
		body := HttpSecurityApiUpdateReportRequestBody{}
		if err := xidlgohttp.GinDecodeBody(c, "application/json", &body); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusBadRequest, "BAD_REQUEST", err.Error())
			return
		}
		req.Body = body.Body
		resp, err := svc.UpdateReport(c.Request.Context(), req)
		if err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusInternalServerError, "INTERNAL", err.Error())
			return
		}

		if err := xidlgohttp.GinEncodeBody(c, "application/json", resp.Return); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusInternalServerError, "ENCODE", err.Error())
		}
	})
	r.GET("/health", func(c *gin.Context) {
		if err := xidlgohttp.GinRequireAccept(c, "application/json"); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusNotAcceptable, "NOT_ACCEPTABLE", err.Error())
			return
		}

		req := &HttpSecurityApiHealthRequest{}
		resp, err := svc.Health(c.Request.Context(), req)
		if err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusInternalServerError, "INTERNAL", err.Error())
			return
		}

		if err := xidlgohttp.GinEncodeBody(c, "application/json", resp.Return); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusInternalServerError, "ENCODE", err.Error())
		}
	})
}

type HttpSecurityApiClient struct {
	baseURL    string
	httpClient *http.Client
	auth       xidlgohttp.ClientAuth
}

func NewHttpSecurityApiClient(baseURL string, httpClient *http.Client, auth xidlgohttp.ClientAuth) *HttpSecurityApiClient {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &HttpSecurityApiClient{baseURL: strings.TrimRight(baseURL, "/"), httpClient: httpClient, auth: auth}
}

func (c *HttpSecurityApiClient) GetReport(ctx context.Context, req *HttpSecurityApiGetReportRequest) (*HttpSecurityApiGetReportResponse, error) {
	requestURL := c.baseURL + formatHttpSecurityApiGetReportPath(req)
	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, err
	}
	httpReq.Header.Set("Accept", "application/json")

	httpReq.Header.Set("X-Trace-Id", req.TraceId)
	xidlgohttp.ApplyClientAuth(httpReq, c.auth, HttpSecurityApiGetReportSecurityRequirements())
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("http %d", resp.StatusCode)
	}
	decoded, err := decodeHttpSecurityApiGetReportResponse(resp)
	if err != nil {
		return nil, err
	}
	return &decoded, nil
}

func (c *HttpSecurityApiClient) UpdateReport(ctx context.Context, req *HttpSecurityApiUpdateReportRequest) (*HttpSecurityApiUpdateReportResponse, error) {
	requestURL := c.baseURL + formatHttpSecurityApiUpdateReportPath(req)
	body := HttpSecurityApiUpdateReportRequestBody{
		Body: req.Body,
	}
	var requestBody bytes.Buffer
	if err := xidlgohttp.MustCodecForMime("application/json").Encode(&requestBody, body); err != nil {
		return nil, err
	}
	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, &requestBody)
	if err != nil {
		return nil, err
	}
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("Accept", "application/json")
	xidlgohttp.ApplyClientAuth(httpReq, c.auth, HttpSecurityApiUpdateReportSecurityRequirements())
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("http %d", resp.StatusCode)
	}
	decoded, err := decodeHttpSecurityApiUpdateReportResponse(resp)
	if err != nil {
		return nil, err
	}
	return &decoded, nil
}

func (c *HttpSecurityApiClient) Health(ctx context.Context, req *HttpSecurityApiHealthRequest) (*HttpSecurityApiHealthResponse, error) {
	requestURL := c.baseURL + formatHttpSecurityApiHealthPath(req)
	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, err
	}
	httpReq.Header.Set("Accept", "application/json")
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("http %d", resp.StatusCode)
	}
	decoded, err := decodeHttpSecurityApiHealthResponse(resp)
	if err != nil {
		return nil, err
	}
	return &decoded, nil
}

type HttpSecurityApiGetReportRequest struct {
	Id      string `xjson:"id" form:"id"`
	TraceId string `xjson:"trace_id" form:"trace_id"`
}

type HttpSecurityApiGetReportResponse struct {
	Return string `xjson:"return"`
}

func HttpSecurityApiGetReportSecurityRequirements() []xidlgohttp.SecurityRequirement {
	return []xidlgohttp.SecurityRequirement{
		{Kind: xidlgohttp.SecurityBasic, Realm: "GetReport"},
		{Kind: xidlgohttp.SecurityAPIKey, Location: xidlgohttp.ApiKeyHeader, Name: "X-Org-Key"},
	}
}

func HttpSecurityApiGetReportDeprecated() xidlgohttp.DeprecatedInfo {
	return xidlgohttp.DeprecatedInfo{
		Deprecated: false,
	}
}

func formatHttpSecurityApiGetReportPath(req *HttpSecurityApiGetReportRequest) string {
	path := "/reports/{id}"
	path = strings.ReplaceAll(path, "{id}", req.Id)
	path = strings.ReplaceAll(path, "{*id}", req.Id)
	return path
}
func decodeHttpSecurityApiGetReportResponse(resp *http.Response) (HttpSecurityApiGetReportResponse, error) {
	out := HttpSecurityApiGetReportResponse{}
	var body string
	if err := xidlgohttp.MustCodecForMime("application/json").Decode(resp.Body, &body); err != nil {
		return out, err
	}
	out.Return = body
	return out, nil
}

type HttpSecurityApiUpdateReportRequest struct {
	Id   string `xjson:"id" form:"id"`
	Body string `xjson:"body" form:"body"`
}

type HttpSecurityApiUpdateReportRequestBody struct {
	Body string `xjson:"body" form:"body"`
}

type HttpSecurityApiUpdateReportResponse struct {
	Return string `xjson:"return"`
}

func HttpSecurityApiUpdateReportSecurityRequirements() []xidlgohttp.SecurityRequirement {
	return []xidlgohttp.SecurityRequirement{
		{Kind: xidlgohttp.SecurityOAuth2, Scopes: []string{"reports:write"}},
	}
}

func HttpSecurityApiUpdateReportDeprecated() xidlgohttp.DeprecatedInfo {
	return xidlgohttp.DeprecatedInfo{
		Deprecated: false,
	}
}

func formatHttpSecurityApiUpdateReportPath(req *HttpSecurityApiUpdateReportRequest) string {
	path := "/reports/{id}"
	path = strings.ReplaceAll(path, "{id}", req.Id)
	path = strings.ReplaceAll(path, "{*id}", req.Id)
	return path
}
func decodeHttpSecurityApiUpdateReportResponse(resp *http.Response) (HttpSecurityApiUpdateReportResponse, error) {
	out := HttpSecurityApiUpdateReportResponse{}
	var body string
	if err := xidlgohttp.MustCodecForMime("application/json").Decode(resp.Body, &body); err != nil {
		return out, err
	}
	out.Return = body
	return out, nil
}

type HttpSecurityApiHealthRequest struct {
}

type HttpSecurityApiHealthResponse struct {
	Return string `xjson:"return"`
}

func HttpSecurityApiHealthSecurityRequirements() []xidlgohttp.SecurityRequirement {
	return []xidlgohttp.SecurityRequirement{}
}

func HttpSecurityApiHealthDeprecated() xidlgohttp.DeprecatedInfo {
	return xidlgohttp.DeprecatedInfo{
		Deprecated: false,
	}
}

func formatHttpSecurityApiHealthPath(req *HttpSecurityApiHealthRequest) string {
	path := "/health"
	return path
}
func decodeHttpSecurityApiHealthResponse(resp *http.Response) (HttpSecurityApiHealthResponse, error) {
	out := HttpSecurityApiHealthResponse{}
	var body string
	if err := xidlgohttp.MustCodecForMime("application/json").Decode(resp.Body, &body); err != nil {
		return out, err
	}
	out.Return = body
	return out, nil
}
