//! Generated by xidlc.
//! xidlc_version: 0.1.0
//! xidlc_timestamp: 2026-02-06 05:44

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unreachable_patterns)]
#![allow(clippy::let_unit_value)]

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::BTreeMap;
use std::ffi::c_void;
use tokio::io::{AsyncRead, AsyncWrite, BufReader};
use tokio::sync::Mutex;
pub trait HelloWorld {
    fn sayHello<'a>(
        &'a self,
        name: String,
    ) -> xidl_jsonrpc::BoxFuture<'a, Result<(), xidl_jsonrpc::Error>>;
}

#[derive(Serialize, Deserialize)]
struct HelloWorldsayHelloParams {
    name: String,
}

pub struct HelloWorldServer<T> {
    inner: T,
}

impl<T> HelloWorldServer<T> {
    pub fn new(inner: T) -> Self {
        Self { inner }
    }
}

impl<T> xidl_jsonrpc::Handler for HelloWorldServer<T>
where
    T: HelloWorld + Send + Sync,
{
    fn handle<'a>(
        &'a self,
        method: &'a str,
        params: Value,
    ) -> xidl_jsonrpc::BoxFuture<'a, Result<Value, xidl_jsonrpc::Error>> {
        Box::pin(async move {
            match method {
                "HelloWorld.sayHello" => {
                    let params: HelloWorldsayHelloParams = serde_json::from_value(params)
                        .map_err(|err| xidl_jsonrpc::Error::invalid_params(err.to_string()))?;
                    let result = self.inner.sayHello(params.name).await?;
                    Ok(serde_json::to_value(result)?)
                }
                _ => Err(xidl_jsonrpc::Error::method_not_found(method)),
            }
        })
    }
}

pub struct HelloWorldClient<R, W> {
    client: Mutex<xidl_jsonrpc::Client<BufReader<R>, W>>,
}

impl<R, W> HelloWorldClient<R, W>
where
    R: AsyncRead + Unpin + Send,
    W: AsyncWrite + Unpin + Send,
{
    pub fn new(reader: R, writer: W) -> Self {
        Self {
            client: Mutex::new(xidl_jsonrpc::Client::new(BufReader::new(reader), writer)),
        }
    }
}

impl<R, W> HelloWorld for HelloWorldClient<R, W>
where
    R: AsyncRead + Unpin + Send,
    W: AsyncWrite + Unpin + Send,
{
    fn sayHello<'a>(
        &'a self,
        name: String,
    ) -> xidl_jsonrpc::BoxFuture<'a, Result<(), xidl_jsonrpc::Error>> {
        let params = HelloWorldsayHelloParams { name };
        Box::pin(async move {
            let mut client = self.client.lock().await;
            client.call("HelloWorld.sayHello", params).await
        })
    }
}
