//! Generated by xidlc.
#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unreachable_patterns)]
#![allow(clippy::let_unit_value)]

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::cell::RefCell;
use std::collections::BTreeMap;
use std::ffi::c_void;
use std::io::{BufReader, Read, Write};

pub trait HelloWorld {
    fn sayHello(&self, name: String) -> Result<(), xidl_jsonrpc::Error>;
}

#[derive(Serialize, Deserialize)]
struct HelloWorldSayHelloParams {
    name: String,
}

pub struct HelloWorldServer<T> {
    inner: T,
}

impl<T> HelloWorldServer<T> {
    pub fn new(inner: T) -> Self {
        Self { inner }
    }
}

impl<T> xidl_jsonrpc::Handler for HelloWorldServer<T>
where
    T: HelloWorld,
{
    fn handle(&self, method: &str, params: Value) -> Result<Value, xidl_jsonrpc::Error> {
        match method {
            "HelloWorld.sayHello" => {
                let params: HelloWorldSayHelloParams = serde_json::from_value(params)
                    .map_err(|err| xidl_jsonrpc::Error::invalid_params(err.to_string()))?;

                let result = self.inner.sayHello(params.name)?;

                Ok(serde_json::to_value(result)?)
            }

            _ => Err(xidl_jsonrpc::Error::method_not_found(method)),
        }
    }
}

pub struct HelloWorldClient<R, W> {
    client: RefCell<xidl_jsonrpc::Client<BufReader<R>, W>>,
}

impl<R, W> HelloWorldClient<R, W>
where
    R: Read,
    W: Write,
{
    pub fn new(reader: R, writer: W) -> Self {
        Self {
            client: RefCell::new(xidl_jsonrpc::Client::new(BufReader::new(reader), writer)),
        }
    }
}

impl<R, W> HelloWorld for HelloWorldClient<R, W>
where
    R: Read,
    W: Write,
{
    fn sayHello(&self, name: String) -> Result<(), xidl_jsonrpc::Error> {
        let params = HelloWorldSayHelloParams { name };
        self.client.borrow_mut().call("HelloWorld.sayHello", params)
    }
}
