use crate::generate::render_const_expr;
use serde_json::json;
use xidl_parser::hir;

pub fn rust_header() -> String {
    [
        "// Generated by idlc",
        "#![allow(dead_code)]",
        "use std::collections::BTreeMap;",
        "use std::ffi::c_void;",
    ]
    .join("\n")
}

pub fn rust_scoped_name(value: &hir::ScopedName) -> String {
    let name = value.name.join("::");
    if value.is_root {
        format!("::{name}")
    } else {
        name
    }
}

pub fn rust_integer_type(value: &hir::IntegerType) -> String {
    match value {
        hir::IntegerType::Char => "i8".to_string(),
        hir::IntegerType::UChar => "u8".to_string(),
        hir::IntegerType::U8 => "u8".to_string(),
        hir::IntegerType::U16 => "u16".to_string(),
        hir::IntegerType::U32 => "u32".to_string(),
        hir::IntegerType::U64 => "u64".to_string(),
        hir::IntegerType::I8 => "i8".to_string(),
        hir::IntegerType::I16 => "i16".to_string(),
        hir::IntegerType::I32 => "i32".to_string(),
        hir::IntegerType::I64 => "i64".to_string(),
    }
}

pub fn rust_const_type(ty: &hir::ConstType) -> String {
    match ty {
        hir::ConstType::IntegerType(value) => rust_integer_type(value),
        hir::ConstType::FloatingPtType => "f64".to_string(),
        hir::ConstType::FixedPtConstType => "f64".to_string(),
        hir::ConstType::CharType => "char".to_string(),
        hir::ConstType::WideCharType => "char".to_string(),
        hir::ConstType::BooleanType => "bool".to_string(),
        hir::ConstType::OctetType => "u8".to_string(),
        hir::ConstType::StringType(_) => "&'static str".to_string(),
        hir::ConstType::WideStringType(_) => "&'static str".to_string(),
        hir::ConstType::ScopedName(value) => rust_scoped_name(value),
        hir::ConstType::SequenceType(_) => "*const c_void".to_string(),
    }
}

pub fn rust_type(ty: &hir::TypeSpec) -> String {
    match ty {
        hir::TypeSpec::SimpleTypeSpec(simple) => match simple {
            hir::SimpleTypeSpec::IntegerType(value) => rust_integer_type(value),
            hir::SimpleTypeSpec::FloatingPtType => "f64".to_string(),
            hir::SimpleTypeSpec::CharType => "char".to_string(),
            hir::SimpleTypeSpec::WideCharType => "char".to_string(),
            hir::SimpleTypeSpec::Boolean => "bool".to_string(),
            hir::SimpleTypeSpec::AnyType => "*mut c_void".to_string(),
            hir::SimpleTypeSpec::ObjectType => "*mut c_void".to_string(),
            hir::SimpleTypeSpec::ValueBaseType => "*mut c_void".to_string(),
            hir::SimpleTypeSpec::ScopedName(value) => rust_scoped_name(value),
        },
        hir::TypeSpec::TemplateTypeSpec(template) => match template {
            hir::TemplateTypeSpec::SequenceType(seq) => {
                format!("Vec<{}>", rust_type(&seq.ty))
            }
            hir::TemplateTypeSpec::StringType(_) => "String".to_string(),
            hir::TemplateTypeSpec::WideStringType(_) => "String".to_string(),
            hir::TemplateTypeSpec::FixedPtType(_) => "f64".to_string(),
            hir::TemplateTypeSpec::MapType(map) => {
                format!(
                    "BTreeMap<{}, {}>",
                    rust_type(&map.key),
                    rust_type(&map.value)
                )
            }
        },
    }
}

pub fn rust_switch_type(value: &hir::SwitchTypeSpec) -> String {
    match value {
        hir::SwitchTypeSpec::IntegerType(ty) => rust_integer_type(ty),
        hir::SwitchTypeSpec::CharType => "char".to_string(),
        hir::SwitchTypeSpec::WideCharType => "char".to_string(),
        hir::SwitchTypeSpec::BooleanType => "bool".to_string(),
        hir::SwitchTypeSpec::ScopedName(value) => rust_scoped_name(value),
        hir::SwitchTypeSpec::OctetType => "u8".to_string(),
    }
}

pub fn rust_literal(value: &hir::Literal) -> String {
    match value {
        hir::Literal::IntegerLiteral(lit) => match lit {
            hir::IntegerLiteral::BinNumber(value) => value.clone(),
            hir::IntegerLiteral::OctNumber(value) => value.clone(),
            hir::IntegerLiteral::DecNumber(value) => value.clone(),
            hir::IntegerLiteral::HexNumber(value) => value.clone(),
        },
        hir::Literal::FloatingPtLiteral(lit) => {
            let sign = lit
                .sign
                .as_ref()
                .map(|value| value.0.as_str())
                .unwrap_or("");
            format!("{}{}.{}", sign, lit.integer.0, lit.fraction.0)
        }
        hir::Literal::CharLiteral(value) => value.clone(),
        hir::Literal::WideCharacterLiteral(value) => {
            value.strip_prefix('L').unwrap_or(value).into()
        }
        hir::Literal::StringLiteral(value) => value.clone(),
        hir::Literal::WideStringLiteral(value) => value.strip_prefix('L').unwrap_or(value).into(),
        hir::Literal::BooleanLiteral(value) => value.to_ascii_lowercase(),
    }
}

pub fn render_const(expr: &hir::ConstExpr) -> String {
    render_const_expr(expr, &rust_scoped_name, &rust_literal)
}

pub fn bitfield_type(value: &hir::BitFieldType) -> String {
    match value {
        hir::BitFieldType::Bool => "bool".to_string(),
        hir::BitFieldType::Octec => "u8".to_string(),
        hir::BitFieldType::SignedInt => "i32".to_string(),
        hir::BitFieldType::UnsignedInt => "u32".to_string(),
    }
}

pub fn array_type(base: &str, dims: &[String]) -> String {
    let mut out = base.to_string();
    for dim in dims.iter().rev() {
        out = format!("[{}; {}]", out, dim);
    }
    out
}

pub fn declarator_dims(decl: &hir::Declarator) -> Vec<String> {
    match decl {
        hir::Declarator::SimpleDeclarator(_) => Vec::new(),
        hir::Declarator::ArrayDeclarator(value) => {
            value.len.iter().map(|len| render_const(&len.0)).collect()
        }
    }
}

pub fn declarator_name(decl: &hir::Declarator) -> String {
    match decl {
        hir::Declarator::SimpleDeclarator(value) => value.0.clone(),
        hir::Declarator::ArrayDeclarator(value) => value.ident.clone(),
    }
}

pub fn type_with_decl(ty: &hir::TypeSpec, decl: &hir::Declarator) -> String {
    let base = rust_type(ty);
    let dims = declarator_dims(decl);
    if dims.is_empty() {
        base
    } else {
        array_type(&base, &dims)
    }
}

pub fn member_json(ty: &hir::TypeSpec, decl: &hir::Declarator) -> serde_json::Value {
    let name = declarator_name(decl);
    let ty = type_with_decl(ty, decl);
    json!({ "ty": ty, "name": name })
}

pub fn typedef_json(base: &str, decl: &hir::Declarator) -> serde_json::Value {
    let name = declarator_name(decl);
    let dims = declarator_dims(decl);
    let ty = if dims.is_empty() {
        base.to_string()
    } else {
        array_type(base, &dims)
    };
    json!({ "ty": ty, "name": name })
}
