use crate::generate::render_const_expr;
use serde_json::json;
use xidl_parser::hir;

pub fn field_for_member(member: &hir::Member, decl: &hir::Declarator) -> serde_json::Value {
    let ty = c_type(&member.ty);
    match decl {
        hir::Declarator::SimpleDeclarator(value) => {
            json!({"ty": ty, "name": &value.0, "dims": Vec::<String>::new()})
        }
        hir::Declarator::ArrayDeclarator(value) => {
            let dims: Vec<_> = value
                .len
                .iter()
                .map(|len| {
                    format!(
                        "[{}]",
                        render_const_expr(&len.0, &c_scoped_name, &c_literal)
                    )
                })
                .collect();
            json!({"ty": ty, "name": &value.ident, "dims": dims})
        }
    }
}

pub fn interface_name(interface: &hir::InterfaceDcl) -> String {
    match interface {
        hir::InterfaceDcl::InterfaceForwardDcl(forward) => forward.ident.clone(),
        hir::InterfaceDcl::InterfaceDef(def) => def.header.ident.clone(),
    }
}

pub fn comment_placeholder(message: &str) -> String {
    format!("/* {message} */")
}

pub fn c_header() -> String {
    [
        "// Generated by idlc",
        "#pragma once",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "#include <wchar.h>",
    ]
    .join("\n")
}

pub fn c_source_header(header_name: &str) -> String {
    format!("#include \"{header_name}\"")
}

pub fn c_const_type(ty: &hir::ConstType) -> String {
    match ty {
        hir::ConstType::IntegerType(value) => c_integer_type(value),
        hir::ConstType::FloatingPtType => "double".to_string(),
        hir::ConstType::FixedPtConstType => "double".to_string(),
        hir::ConstType::CharType => "char".to_string(),
        hir::ConstType::WideCharType => "wchar_t".to_string(),
        hir::ConstType::BooleanType => "bool".to_string(),
        hir::ConstType::OctetType => "uint8_t".to_string(),
        hir::ConstType::StringType(_) => "const char *".to_string(),
        hir::ConstType::WideStringType(_) => "const wchar_t *".to_string(),
        hir::ConstType::ScopedName(value) => c_scoped_name_hir(value),
        hir::ConstType::SequenceType(_) => "void *".to_string(),
    }
}

pub fn c_type(ty: &hir::TypeSpec) -> String {
    match ty {
        hir::TypeSpec::SimpleTypeSpec(simple) => match simple {
            hir::SimpleTypeSpec::IntegerType(value) => c_integer_type(value),
            hir::SimpleTypeSpec::FloatingPtType => "double".to_string(),
            hir::SimpleTypeSpec::CharType => "char".to_string(),
            hir::SimpleTypeSpec::WideCharType => "wchar_t".to_string(),
            hir::SimpleTypeSpec::Boolean => "bool".to_string(),
            hir::SimpleTypeSpec::AnyType => "void *".to_string(),
            hir::SimpleTypeSpec::ObjectType => "void *".to_string(),
            hir::SimpleTypeSpec::ValueBaseType => "void *".to_string(),
            hir::SimpleTypeSpec::ScopedName(value) => c_scoped_name_hir(value),
        },
        hir::TypeSpec::TemplateTypeSpec(template) => match template {
            hir::TemplateTypeSpec::SequenceType(_) => "void *".to_string(),
            hir::TemplateTypeSpec::StringType(_) => "char *".to_string(),
            hir::TemplateTypeSpec::WideStringType(_) => "wchar_t *".to_string(),
            hir::TemplateTypeSpec::FixedPtType(_) => "double".to_string(),
            hir::TemplateTypeSpec::MapType(_) => "void *".to_string(),
        },
    }
}

pub fn c_integer_type(value: &hir::IntegerType) -> String {
    match value {
        hir::IntegerType::Char => "int8_t".to_string(),
        hir::IntegerType::UChar => "uint8_t".to_string(),
        hir::IntegerType::U8 => "uint8_t".to_string(),
        hir::IntegerType::U16 => "uint16_t".to_string(),
        hir::IntegerType::U32 => "uint32_t".to_string(),
        hir::IntegerType::U64 => "uint64_t".to_string(),
        hir::IntegerType::I8 => "int8_t".to_string(),
        hir::IntegerType::I16 => "int16_t".to_string(),
        hir::IntegerType::I32 => "int32_t".to_string(),
        hir::IntegerType::I64 => "int64_t".to_string(),
    }
}

pub fn c_scoped_name_hir(value: &hir::ScopedName) -> String {
    value
        .name
        .iter()
        .map(|part| part.as_str())
        .collect::<Vec<_>>()
        .join("_")
}

pub fn c_scoped_name(value: &hir::ScopedName) -> String {
    c_scoped_name_hir(value)
}

pub fn c_literal(value: &hir::Literal) -> String {
    match value {
        hir::Literal::IntegerLiteral(lit) => match lit {
            hir::IntegerLiteral::BinNumber(value) => value.clone(),
            hir::IntegerLiteral::OctNumber(value) => value.clone(),
            hir::IntegerLiteral::DecNumber(value) => value.clone(),
            hir::IntegerLiteral::HexNumber(value) => value.clone(),
        },
        hir::Literal::FloatingPtLiteral(lit) => {
            let sign = lit
                .sign
                .as_ref()
                .map(|value| value.0.as_str())
                .unwrap_or("");
            format!("{}{}.{}", sign, lit.integer.0, lit.fraction.0)
        }
        hir::Literal::CharLiteral(value) => value.clone(),
        hir::Literal::WideCharacterLiteral(value) => value.clone(),
        hir::Literal::StringLiteral(value) => value.clone(),
        hir::Literal::WideStringLiteral(value) => value.clone(),
        hir::Literal::BooleanLiteral(value) => value.to_ascii_lowercase(),
    }
}

pub fn c_switch_type(value: &hir::SwitchTypeSpec) -> String {
    match value {
        hir::SwitchTypeSpec::IntegerType(ty) => c_integer_type(ty),
        hir::SwitchTypeSpec::CharType => "char".to_string(),
        hir::SwitchTypeSpec::WideCharType => "wchar_t".to_string(),
        hir::SwitchTypeSpec::BooleanType => "bool".to_string(),
        hir::SwitchTypeSpec::ScopedName(value) => c_scoped_name_hir(value),
        hir::SwitchTypeSpec::OctetType => "uint8_t".to_string(),
    }
}

pub fn c_element_type_name(value: &hir::ElementSpecTy) -> String {
    match value {
        hir::ElementSpecTy::TypeSpec(ty) => c_type(ty),
        hir::ElementSpecTy::ConstrTypeDcl(constr) => match constr {
            hir::ConstrTypeDcl::StructForwardDcl(def) => def.ident.clone(),
            hir::ConstrTypeDcl::StructDcl(def) => def.ident.clone(),
            hir::ConstrTypeDcl::EnumDcl(def) => def.ident.clone(),
            hir::ConstrTypeDcl::UnionForwardDcl(def) => def.ident.clone(),
            hir::ConstrTypeDcl::UnionDef(def) => def.ident.clone(),
            hir::ConstrTypeDcl::BitsetDcl(def) => def.ident.clone(),
            hir::ConstrTypeDcl::BitmaskDcl(def) => def.ident.clone(),
        },
    }
}

pub fn declarator_info(decl: &hir::Declarator) -> (String, Vec<String>) {
    match decl {
        hir::Declarator::SimpleDeclarator(value) => (value.0.clone(), Vec::new()),
        hir::Declarator::ArrayDeclarator(value) => {
            let dims = value
                .len
                .iter()
                .map(|len| {
                    format!(
                        "[{}]",
                        render_const_expr(&len.0, &c_scoped_name, &c_literal)
                    )
                })
                .collect();
            (value.ident.clone(), dims)
        }
    }
}

pub fn collect_inline_defs(
    constr: &hir::ConstrTypeDcl,
    renderer: &crate::generate::c::CRenderer,
) -> crate::error::IdlcResult<crate::generate::c::CRenderOutput> {
    use crate::generate::c::CRender;
    match constr {
        hir::ConstrTypeDcl::StructDcl(def) => def.render(renderer),
        hir::ConstrTypeDcl::EnumDcl(def) => def.render(renderer),
        hir::ConstrTypeDcl::UnionDef(def) => def.render(renderer),
        hir::ConstrTypeDcl::BitsetDcl(def) => def.render(renderer),
        hir::ConstrTypeDcl::BitmaskDcl(def) => def.render(renderer),
        _ => Ok(crate::generate::c::CRenderOutput::default()),
    }
}

pub fn bitfield_type(value: &hir::BitFieldType) -> String {
    match value {
        hir::BitFieldType::Bool => "bool".to_string(),
        hir::BitFieldType::Octec => "uint8_t".to_string(),
        hir::BitFieldType::SignedInt => "int32_t".to_string(),
        hir::BitFieldType::UnsignedInt => "uint32_t".to_string(),
    }
}
