use crate::generate::c::util::{c_literal, c_scoped_name, c_scoped_name_hir};
use crate::generate::render_const_expr;
use serde_json::json;
use xidl_parser::hir;

pub fn xcdr_header(base_header: &str) -> String {
    [
        "// Generated by idlc",
        "#pragma once",
        &format!("#include \"{}\"", base_header),
        "#include \"xidl_xcdr.h\"",
        "#include <stddef.h>",
    ]
    .join("\n")
}

pub fn xcdr_source_header(header_name: &str) -> String {
    format!("#include \"{}\"", header_name)
}

#[derive(Clone)]
pub(crate) enum FieldKind {
    Primitive {
        serialize_fn: &'static str,
        deserialize_fn: &'static str,
    },
    Custom {
        type_name: String,
    },
    Unsupported {
        reason: String,
    },
}

pub(crate) fn type_kind(ty: &hir::TypeSpec) -> FieldKind {
    match ty {
        hir::TypeSpec::SimpleTypeSpec(simple) => match simple {
            hir::SimpleTypeSpec::IntegerType(value) => match value {
                hir::IntegerType::Char | hir::IntegerType::I8 => FieldKind::Primitive {
                    serialize_fn: "cdr_serializer_write_i8",
                    deserialize_fn: "cdr_deserializer_read_i8",
                },
                hir::IntegerType::UChar | hir::IntegerType::U8 => FieldKind::Primitive {
                    serialize_fn: "cdr_serializer_write_u8",
                    deserialize_fn: "cdr_deserializer_read_u8",
                },
                hir::IntegerType::U16 => FieldKind::Primitive {
                    serialize_fn: "cdr_serializer_write_u16",
                    deserialize_fn: "cdr_deserializer_read_u16_le",
                },
                hir::IntegerType::U32 => FieldKind::Primitive {
                    serialize_fn: "cdr_serializer_write_u32",
                    deserialize_fn: "cdr_deserializer_read_u32_le",
                },
                hir::IntegerType::U64 => FieldKind::Primitive {
                    serialize_fn: "cdr_serializer_write_u64",
                    deserialize_fn: "cdr_deserializer_read_u64_le",
                },
                hir::IntegerType::I16 => FieldKind::Primitive {
                    serialize_fn: "cdr_serializer_write_i16",
                    deserialize_fn: "cdr_deserializer_read_i16_le",
                },
                hir::IntegerType::I32 => FieldKind::Primitive {
                    serialize_fn: "cdr_serializer_write_i32",
                    deserialize_fn: "cdr_deserializer_read_i32_le",
                },
                hir::IntegerType::I64 => FieldKind::Primitive {
                    serialize_fn: "cdr_serializer_write_i64",
                    deserialize_fn: "cdr_deserializer_read_i64_le",
                },
            },
            hir::SimpleTypeSpec::FloatingPtType => FieldKind::Primitive {
                serialize_fn: "cdr_serializer_write_f64",
                deserialize_fn: "cdr_deserializer_read_f64_le",
            },
            hir::SimpleTypeSpec::CharType => FieldKind::Primitive {
                serialize_fn: "cdr_serializer_write_i8",
                deserialize_fn: "cdr_deserializer_read_i8",
            },
            hir::SimpleTypeSpec::WideCharType => FieldKind::Primitive {
                serialize_fn: "cdr_serializer_write_u32",
                deserialize_fn: "cdr_deserializer_read_u32_le",
            },
            hir::SimpleTypeSpec::Boolean => FieldKind::Primitive {
                serialize_fn: "cdr_serializer_write_bool",
                deserialize_fn: "cdr_deserializer_read_bool",
            },
            hir::SimpleTypeSpec::ScopedName(value) => FieldKind::Custom {
                type_name: c_scoped_name_hir(value),
            },
            _ => FieldKind::Unsupported {
                reason: "unsupported simple type".to_string(),
            },
        },
        hir::TypeSpec::TemplateTypeSpec(_) => FieldKind::Unsupported {
            reason: "unsupported template type".to_string(),
        },
    }
}

pub(crate) fn switch_kind(ty: &hir::SwitchTypeSpec) -> FieldKind {
    match ty {
        hir::SwitchTypeSpec::IntegerType(value) => type_kind(&hir::TypeSpec::SimpleTypeSpec(
            hir::SimpleTypeSpec::IntegerType(value.clone()),
        )),
        hir::SwitchTypeSpec::CharType => FieldKind::Primitive {
            serialize_fn: "cdr_serializer_write_i8",
            deserialize_fn: "cdr_deserializer_read_i8",
        },
        hir::SwitchTypeSpec::WideCharType => FieldKind::Primitive {
            serialize_fn: "cdr_serializer_write_u32",
            deserialize_fn: "cdr_deserializer_read_u32_le",
        },
        hir::SwitchTypeSpec::BooleanType => FieldKind::Primitive {
            serialize_fn: "cdr_serializer_write_bool",
            deserialize_fn: "cdr_deserializer_read_bool",
        },
        hir::SwitchTypeSpec::OctetType => FieldKind::Primitive {
            serialize_fn: "cdr_serializer_write_u8",
            deserialize_fn: "cdr_deserializer_read_u8",
        },
        hir::SwitchTypeSpec::ScopedName(value) => FieldKind::Custom {
            type_name: c_scoped_name_hir(value),
        },
    }
}

pub(crate) fn element_kind(ty: &hir::ElementSpecTy) -> FieldKind {
    match ty {
        hir::ElementSpecTy::TypeSpec(spec) => type_kind(spec),
        hir::ElementSpecTy::ConstrTypeDcl(constr) => FieldKind::Custom {
            type_name: constr_type_name(constr),
        },
    }
}

pub(crate) fn constr_type_name(constr: &hir::ConstrTypeDcl) -> String {
    match constr {
        hir::ConstrTypeDcl::StructForwardDcl(def) => def.ident.clone(),
        hir::ConstrTypeDcl::StructDcl(def) => def.ident.clone(),
        hir::ConstrTypeDcl::EnumDcl(def) => def.ident.clone(),
        hir::ConstrTypeDcl::UnionForwardDcl(def) => def.ident.clone(),
        hir::ConstrTypeDcl::UnionDef(def) => def.ident.clone(),
        hir::ConstrTypeDcl::BitsetDcl(def) => def.ident.clone(),
        hir::ConstrTypeDcl::BitmaskDcl(def) => def.ident.clone(),
    }
}

pub(crate) fn type_kind_from_c(ty: &str) -> FieldKind {
    match ty {
        "uint8_t" => FieldKind::Primitive {
            serialize_fn: "cdr_serializer_write_u8",
            deserialize_fn: "cdr_deserializer_read_u8",
        },
        "int8_t" => FieldKind::Primitive {
            serialize_fn: "cdr_serializer_write_i8",
            deserialize_fn: "cdr_deserializer_read_i8",
        },
        "uint16_t" => FieldKind::Primitive {
            serialize_fn: "cdr_serializer_write_u16",
            deserialize_fn: "cdr_deserializer_read_u16_le",
        },
        "int16_t" => FieldKind::Primitive {
            serialize_fn: "cdr_serializer_write_i16",
            deserialize_fn: "cdr_deserializer_read_i16_le",
        },
        "uint32_t" => FieldKind::Primitive {
            serialize_fn: "cdr_serializer_write_u32",
            deserialize_fn: "cdr_deserializer_read_u32_le",
        },
        "int32_t" => FieldKind::Primitive {
            serialize_fn: "cdr_serializer_write_i32",
            deserialize_fn: "cdr_deserializer_read_i32_le",
        },
        "uint64_t" => FieldKind::Primitive {
            serialize_fn: "cdr_serializer_write_u64",
            deserialize_fn: "cdr_deserializer_read_u64_le",
        },
        "int64_t" => FieldKind::Primitive {
            serialize_fn: "cdr_serializer_write_i64",
            deserialize_fn: "cdr_deserializer_read_i64_le",
        },
        "bool" => FieldKind::Primitive {
            serialize_fn: "cdr_serializer_write_bool",
            deserialize_fn: "cdr_deserializer_read_bool",
        },
        _ => FieldKind::Unsupported {
            reason: format!("unsupported bitfield type: {}", ty),
        },
    }
}

pub(crate) fn declarator_info(decl: &hir::Declarator) -> (String, Vec<String>) {
    match decl {
        hir::Declarator::SimpleDeclarator(value) => (value.0.clone(), Vec::new()),
        hir::Declarator::ArrayDeclarator(value) => {
            let dims = value
                .len
                .iter()
                .map(|len| render_const_expr(&len.0, &c_scoped_name, &c_literal))
                .collect();
            (value.ident.clone(), dims)
        }
    }
}

pub(crate) fn kind_json(kind: &FieldKind) -> serde_json::Value {
    match kind {
        FieldKind::Primitive {
            serialize_fn,
            deserialize_fn,
        } => json!({
            "kind": "primitive",
            "serialize_fn": serialize_fn,
            "deserialize_fn": deserialize_fn,
        }),
        FieldKind::Custom { type_name } => json!({
            "kind": "custom",
            "type_name": type_name,
        }),
        FieldKind::Unsupported { reason } => json!({
            "kind": "unsupported",
            "reason": reason,
        }),
    }
}
