//! Generated by xidlc.
#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]

use std::collections::BTreeMap;
use std::ffi::c_void;


pub mod DDS {
    pub mod XTypes {
        pub type EquivalenceKind = u8;
        pub const EK_MINIMAL: u8 = 0xF1;
        pub const EK_COMPLETE: u8 = 0xF2;
        pub const EK_BOTH: u8 = 0xF3;
        pub type TypeKind = u8;
        pub const TK_NONE: u8 = 0x00;
        pub const TK_BOOLEAN: u8 = 0x01;
        pub const TK_BYTE: u8 = 0x02;
        pub const TK_INT16: u8 = 0x03;
        pub const TK_INT32: u8 = 0x04;
        pub const TK_INT64: u8 = 0x05;
        pub const TK_UINT16: u8 = 0x06;
        pub const TK_UINT32: u8 = 0x07;
        pub const TK_UINT64: u8 = 0x08;
        pub const TK_FLOAT32: u8 = 0x09;
        pub const TK_FLOAT64: u8 = 0x0A;
        pub const TK_FLOAT128: u8 = 0x0B;
        pub const TK_CHAR8: u8 = 0x10;
        pub const TK_CHAR16: u8 = 0x11;
        pub const TK_STRING8: u8 = 0x20;
        pub const TK_STRING16: u8 = 0x21;
        pub const TK_ALIAS: u8 = 0x30;
        pub const TK_ENUM: u8 = 0x40;
        pub const TK_BITMASK: u8 = 0x41;
        pub const TK_ANNOTATION: u8 = 0x50;
        pub const TK_STRUCTURE: u8 = 0x51;
        pub const TK_UNION: u8 = 0x52;
        pub const TK_BITSET: u8 = 0x53;
        pub const TK_SEQUENCE: u8 = 0x60;
        pub const TK_ARRAY: u8 = 0x61;
        pub const TK_MAP: u8 = 0x62;
        pub type TypeIdentiferKind = u8;
        pub const TI_STRING8_SMALL: u8 = 0x70;
        pub const TI_STRING8_LARGE: u8 = 0x71;
        pub const TI_STRING16_SMALL: u8 = 0x72;
        pub const TI_STRING16_LARGE: u8 = 0x73;
        pub const TI_PLAIN_SEQUENCE_SMALL: u8 = 0x80;
        pub const TI_PLAIN_SEQUENCE_LARGE: u8 = 0x81;
        pub const TI_PLAIN_ARRAY_SMALL: u8 = 0x90;
        pub const TI_PLAIN_ARRAY_LARGE: u8 = 0x91;
        pub const TI_PLAIN_MAP_SMALL: u8 = 0xA0;
        pub const TI_PLAIN_MAP_LARGE: u8 = 0xA1;
        pub const TI_STRONGLY_CONNECTED_COMPONENT: u8 = 0xB0;
        pub const MEMBER_NAME_MAX_LENGTH: i32 = 256;
        pub type MemberName = String;
        pub const TYPE_NAME_MAX_LENGTH: i32 = 256;
        pub type QualifiedTypeName = String;
        pub type PrimitiveTypeId = u8;
        pub type EquivalenceHash = [u8; 14];
        pub type NameHash = [u8; 4];
        pub type LBound = u32;
        pub type LBoundSeq = Vec<LBound>;
        pub const INVALID_LBOUND: LBound = 0;
        pub type SBound = u8;
        pub type SBoundSeq = Vec<SBound>;
        pub const INVALID_SBOUND: SBound = 0;
        pub struct TypeObjectHashId {
            pub _d: u8,
        
            pub hash: Option<Box<EquivalenceHash>>,
        
        }
        pub struct MemberFlag {
            pub value: u32,
        }
        
        impl MemberFlag {
        
            pub const TRY_CONSTRUCT1: u32 = 1u32 << 0;
        
            pub const TRY_CONSTRUCT2: u32 = 1u32 << 1;
        
            pub const IS_EXTERNAL: u32 = 1u32 << 2;
        
            pub const IS_OPTIONAL: u32 = 1u32 << 3;
        
            pub const IS_MUST_UNDERSTAND: u32 = 1u32 << 4;
        
            pub const IS_KEY: u32 = 1u32 << 5;
        
            pub const IS_DEFAULT: u32 = 1u32 << 6;
        
        }
        pub type CollectionElementFlag = MemberFlag;
        pub type StructMemberFlag = MemberFlag;
        pub type UnionMemberFlag = MemberFlag;
        pub type UnionDiscriminatorFlag = MemberFlag;
        pub type EnumeratedLiteralFlag = MemberFlag;
        pub type AnnotationParameterFlag = MemberFlag;
        pub type AliasMemberFlag = MemberFlag;
        pub type BitflagFlag = MemberFlag;
        pub type BitsetMemberFlag = MemberFlag;
        pub const MemberFlagMinimalMask: u16 = 0x003f;
        pub struct TypeFlag {
            pub value: u32,
        }
        
        impl TypeFlag {
        
            pub const IS_FINAL: u32 = 1u32 << 0;
        
            pub const IS_APPENDABLE: u32 = 1u32 << 1;
        
            pub const IS_MUTABLE: u32 = 1u32 << 2;
        
            pub const IS_NESTED: u32 = 1u32 << 3;
        
            pub const IS_AUTOID_HASH: u32 = 1u32 << 4;
        
        }
        pub type StructTypeFlag = TypeFlag;
        pub type UnionTypeFlag = TypeFlag;
        pub type CollectionTypeFlag = TypeFlag;
        pub type AnnotationTypeFlag = TypeFlag;
        pub type AliasTypeFlag = TypeFlag;
        pub type EnumTypeFlag = TypeFlag;
        pub type BitmaskTypeFlag = TypeFlag;
        pub type BitsetTypeFlag = TypeFlag;
        pub const TypeFlagMinimalMask: u16 = 0x0007;
        pub struct StringSTypeDefn {
        
        
            pub bound: Box<SBound>,
        
        }
        pub struct StringLTypeDefn {
        
        
            pub bound: Box<LBound>,
        
        }
        pub struct PlainCollectionHeader {
        
        
            pub equiv_kind: Box<EquivalenceKind>,
        
            pub element_flags: Box<CollectionElementFlag>,
        
        }
        pub struct PlainSequenceSElemDefn {
        
        
            pub header: Box<PlainCollectionHeader>,
        
            pub bound: Box<SBound>,
        
            pub element_identifier: Box<TypeIdentifier>,
        
        }
        pub struct PlainSequenceLElemDefn {
        
        
            pub header: Box<PlainCollectionHeader>,
        
            pub bound: Box<LBound>,
        
            pub element_identifier: Box<TypeIdentifier>,
        
        }
        pub struct PlainArraySElemDefn {
        
        
            pub header: Box<PlainCollectionHeader>,
        
            pub array_bound_seq: Box<SBoundSeq>,
        
            pub element_identifier: Box<TypeIdentifier>,
        
        }
        pub struct PlainArrayLElemDefn {
        
        
            pub header: Box<PlainCollectionHeader>,
        
            pub array_bound_seq: Box<LBoundSeq>,
        
            pub element_identifier: Box<TypeIdentifier>,
        
        }
        pub struct PlainMapSTypeDefn {
        
        
            pub header: Box<PlainCollectionHeader>,
        
            pub bound: Box<SBound>,
        
            pub element_identifier: Box<TypeIdentifier>,
        
            pub key_flags: Box<CollectionElementFlag>,
        
            pub key_identifier: Box<TypeIdentifier>,
        
        }
        pub struct PlainMapLTypeDefn {
        
        
            pub header: Box<PlainCollectionHeader>,
        
            pub bound: Box<LBound>,
        
            pub element_identifier: Box<TypeIdentifier>,
        
            pub key_flags: Box<CollectionElementFlag>,
        
            pub key_identifier: Box<TypeIdentifier>,
        
        }
        pub struct StronglyConnectedComponentId {
        
        
            pub sc_component_id: Box<TypeObjectHashId>,
        
            pub scc_length: i32,
        
            pub scc_index: i32,
        
        }
        pub struct ExtendedTypeDefn {
        
        
        }
        pub struct TypeIdentifier {
            pub _d: u8,
        
            pub string_sdefn: Option<Box<StringSTypeDefn>>,
        
            pub string_ldefn: Option<Box<StringLTypeDefn>>,
        
            pub seq_sdefn: Option<Box<PlainSequenceSElemDefn>>,
        
            pub seq_ldefn: Option<Box<PlainSequenceLElemDefn>>,
        
            pub array_sdefn: Option<Box<PlainArraySElemDefn>>,
        
            pub array_ldefn: Option<Box<PlainArrayLElemDefn>>,
        
            pub map_sdefn: Option<Box<PlainMapSTypeDefn>>,
        
            pub map_ldefn: Option<Box<PlainMapLTypeDefn>>,
        
            pub sc_component_id: Option<Box<StronglyConnectedComponentId>>,
        
            pub equivalence_hash: Option<Box<EquivalenceHash>>,
        
            pub extended_defn: Option<Box<ExtendedTypeDefn>>,
        
        }
        pub type TypeIdentifierSeq = Vec<TypeIdentifier>;
        pub type MemberId = u32;
        pub const ANNOTATION_STR_VALUE_MAX_LEN: u32 = 128;
        pub const ANNOTATION_OCTETSEC_VALUE_MAX_LEN: u32 = 128;
        pub struct ExtendedAnnotationParameterValue {
        
        
        }
        pub struct AnnotationParameterValue {
            pub _d: u8,
        
            pub boolean_value: Option<bool>,
        
            pub byte_value: Option<u8>,
        
            pub int16_value: Option<i16>,
        
            pub uint_16_value: Option<u16>,
        
            pub int32_value: Option<i32>,
        
            pub uint32_value: Option<u32>,
        
            pub int64_value: Option<i64>,
        
            pub uint64_value: Option<u64>,
        
            pub float32_value: Option<f64>,
        
            pub float64_value: Option<f64>,
        
            pub float128_value: Option<f64>,
        
            pub char_value: Option<char>,
        
            pub wchar_value: Option<char>,
        
            pub enumerated_value: Option<i32>,
        
            pub string8_value: Option<String>,
        
            pub string16_value: Option<String>,
        
            pub extended_value: Option<Box<ExtendedAnnotationParameterValue>>,
        
        }
        pub struct AppliedAnnotationParameter {
        
        
            pub paramname_hash: Box<NameHash>,
        
            pub value: Box<AnnotationParameterValue>,
        
        }
        pub type AppliedAnnotationParameterSeq = Vec<AppliedAnnotationParameter>;
        pub struct AppliedAnnotation {
        
        
            pub annotation_typeid: Box<TypeIdentifier>,
        
            pub param_seq: Box<AppliedAnnotationParameterSeq>,
        
        }
        pub type AppliedAnnotationSeq = Vec<AppliedAnnotation>;
        pub struct AppliedVerbatimAnnotation {
        
        
            pub placement: String,
        
            pub language: String,
        
            pub text: String,
        
        }
        pub struct AppliedBuiltinMemberAnnotations {
        
        
            pub unit: String,
        
            pub min: Box<AnnotationParameterValue>,
        
            pub max: Box<AnnotationParameterValue>,
        
            pub hash_id: String,
        
        }
        pub struct CommonStructMember {
        
        
            pub member_id: Box<MemberId>,
        
            pub member_flags: Box<StructMemberFlag>,
        
            pub member_type_id: Box<TypeIdentifier>,
        
        }
        pub struct CompleteMemberDetail {
        
        
            pub name: Box<MemberName>,
        
            pub ann_builtin: Box<AppliedBuiltinMemberAnnotations>,
        
            pub ann_custom: Box<AppliedAnnotationSeq>,
        
        }
        pub struct MinimalMemberDetail {
        
        
            pub name_hash: Box<NameHash>,
        
        }
        pub struct CompleteStructMember {
        
        
            pub common: Box<CommonStructMember>,
        
            pub detail: Box<CompleteMemberDetail>,
        
        }
        pub type CompleteStructMemberSeq = Vec<CompleteStructMember>;
        pub struct MinimalStructMember {
        
        
            pub common: Box<CommonStructMember>,
        
            pub detail: Box<MinimalMemberDetail>,
        
        }
        pub type MinimalStructMemberSeq = Vec<MinimalStructMember>;
        pub struct AppliedBuiltinTypeAnnotations {
        
        
            pub verbatim: Box<AppliedVerbatimAnnotation>,
        
        }
        pub struct MinimalTypeDetail {
        
        
        }
        pub struct CompleteTypeDetail {
        
        
            pub ann_builtin: Box<AppliedBuiltinTypeAnnotations>,
        
            pub ann_custom: Box<AppliedAnnotationSeq>,
        
            pub type_name: Box<QualifiedTypeName>,
        
        }
        pub struct CompleteStructHeader {
        
        
            pub base_type: Box<TypeIdentifier>,
        
            pub detail: Box<CompleteTypeDetail>,
        
        }
        pub struct MinimalStructHeader {
        
        
            pub base_type: Box<TypeIdentifier>,
        
            pub detail: Box<MinimalTypeDetail>,
        
        }
        pub struct CompleteStructType {
        
        
            pub struct_flags: Box<StructTypeFlag>,
        
            pub header: Box<CompleteStructHeader>,
        
            pub member_seq: Box<CompleteStructMemberSeq>,
        
        }
        pub struct MinimalStructType {
        
        
            pub struct_flags: Box<StructTypeFlag>,
        
            pub header: Box<MinimalStructHeader>,
        
            pub member_seq: Box<MinimalStructMemberSeq>,
        
        }
        pub type UnionCaseLabelSeq = Vec<i32>;
        pub struct CommonUnionMember {
        
        
            pub member_id: Box<MemberId>,
        
            pub member_flags: Box<UnionMemberFlag>,
        
            pub type_id: Box<TypeIdentifier>,
        
            pub label_seq: Box<UnionCaseLabelSeq>,
        
        }
        pub struct CompleteUnionMember {
        
        
            pub common: Box<CommonUnionMember>,
        
            pub detail: Box<CompleteMemberDetail>,
        
        }
        pub type CompleteUnionMemberSeq = Vec<CompleteUnionMember>;
        pub struct MinimalUnionMember {
        
        
            pub common: Box<CommonUnionMember>,
        
            pub detail: Box<MinimalMemberDetail>,
        
        }
        pub type MinimalUnionMemberSeq = Vec<MinimalUnionMember>;
        pub struct CommonDiscriminatorMember {
        
        
            pub member_flags: Box<UnionDiscriminatorFlag>,
        
            pub type_id: Box<TypeIdentifier>,
        
        }
        pub struct CompleteDiscriminatorMember {
        
        
            pub common: Box<CommonDiscriminatorMember>,
        
            pub ann_builtin: Box<AppliedBuiltinTypeAnnotations>,
        
            pub ann_custom: Box<AppliedAnnotationSeq>,
        
        }
        pub struct MinimalDiscriminatorMember {
        
        
            pub common: Box<CommonDiscriminatorMember>,
        
        }
        pub struct CompleteUnionHeader {
        
        
            pub detail: Box<CompleteTypeDetail>,
        
        }
        pub struct MinimalUnionHeader {
        
        
            pub detail: Box<MinimalTypeDetail>,
        
        }
        pub struct CompleteUnionType {
        
        
            pub union_flags: Box<UnionTypeFlag>,
        
            pub header: Box<CompleteUnionHeader>,
        
            pub discriminator: Box<CompleteDiscriminatorMember>,
        
            pub member_seq: Box<CompleteUnionMemberSeq>,
        
        }
        pub struct MinimalUnionType {
        
        
            pub union_flags: Box<UnionTypeFlag>,
        
            pub header: Box<MinimalUnionHeader>,
        
            pub discriminator: Box<MinimalDiscriminatorMember>,
        
            pub member_seq: Box<MinimalUnionMemberSeq>,
        
        }
        pub struct CommonAnnotationParameter {
        
        
            pub member_flags: Box<AnnotationParameterFlag>,
        
            pub member_type_id: Box<TypeIdentifier>,
        
        }
        pub struct CompleteAnnotationParameter {
        
        
            pub common: Box<CommonAnnotationParameter>,
        
            pub name: Box<MemberName>,
        
            pub default_value: Box<AnnotationParameterValue>,
        
        }
        pub type CompleteAnnotationParameterSeq = Vec<CompleteAnnotationParameter>;
        pub struct MinimalAnnotationParameter {
        
        
            pub common: Box<CommonAnnotationParameter>,
        
            pub name_hash: Box<NameHash>,
        
            pub default_value: Box<AnnotationParameterValue>,
        
        }
        pub type MinimalAnnotationParameterSeq = Vec<MinimalAnnotationParameter>;
        pub struct CompleteAnnotationHeader {
        
        
            pub annotation_name: Box<QualifiedTypeName>,
        
        }
        pub struct MinimalAnnotationHeader {
        
        
        }
        pub struct CompleteAnnotationType {
        
        
            pub annotation_flag: Box<AnnotationTypeFlag>,
        
            pub header: Box<CompleteAnnotationHeader>,
        
            pub member_seq: Box<CompleteAnnotationParameterSeq>,
        
        }
        pub struct MinimalAnnotationType {
        
        
            pub annotation_flag: Box<AnnotationTypeFlag>,
        
            pub header: Box<MinimalAnnotationHeader>,
        
            pub member_seq: Box<MinimalAnnotationParameterSeq>,
        
        }
        pub struct CommonAliasBody {
        
        
            pub related_flags: Box<AliasMemberFlag>,
        
            pub related_type: Box<TypeIdentifier>,
        
        }
        pub struct CompleteAliasBody {
        
        
            pub common: Box<CommonAliasBody>,
        
            pub ann_builtin: Box<AppliedBuiltinMemberAnnotations>,
        
            pub ann_custom: Box<AppliedAnnotationSeq>,
        
        }
        pub struct MinimalAliasBody {
        
        
            pub common: Box<CommonAliasBody>,
        
        }
        pub struct CompleteAliasHeader {
        
        
            pub detail: Box<CompleteTypeDetail>,
        
        }
        pub struct MinimalAliasHeader {
        
        
        }
        pub struct CompleteAliasType {
        
        
            pub alias_flags: Box<AliasTypeFlag>,
        
            pub header: Box<CompleteAliasHeader>,
        
            pub body: Box<CompleteAliasBody>,
        
        }
        pub struct MinimalAliasType {
        
        
            pub alias_flags: Box<AliasTypeFlag>,
        
            pub header: Box<MinimalAliasHeader>,
        
            pub body: Box<MinimalAliasBody>,
        
        }
        pub struct CompleteElementDetail {
        
        
            pub ann_builtin: Box<AppliedBuiltinMemberAnnotations>,
        
            pub ann_custom: Box<AppliedAnnotationSeq>,
        
        }
        pub struct CommonCollectionElement {
        
        
            pub element_flags: Box<CollectionElementFlag>,
        
            pub r#type: Box<TypeIdentifier>,
        
        }
        pub struct CompleteCollectionElement {
        
        
            pub common: Box<CommonCollectionElement>,
        
            pub detail: Box<CompleteElementDetail>,
        
        }
        pub struct MinimalCollectionElement {
        
        
            pub common: Box<CommonCollectionElement>,
        
        }
        pub struct CommonCollectionHeader {
        
        
            pub bound: Box<LBound>,
        
        }
        pub struct CompleteCollectionHeader {
        
        
            pub common: Box<CommonCollectionHeader>,
        
            pub detail: Box<CompleteTypeDetail>,
        
        }
        pub struct MinimalCollectionHeader {
        
        
            pub common: Box<CommonCollectionHeader>,
        
        }
        pub struct CompleteSequenceType {
        
        
            pub collection_flag: Box<CollectionTypeFlag>,
        
            pub header: Box<CompleteCollectionHeader>,
        
            pub element: Box<CompleteCollectionElement>,
        
        }
        pub struct MinimalSequenceType {
        
        
            pub collection_flag: Box<CollectionTypeFlag>,
        
            pub header: Box<MinimalCollectionHeader>,
        
            pub element: Box<MinimalCollectionElement>,
        
        }
        pub struct CommonArrayHeader {
        
        
            pub bound_seq: Box<LBoundSeq>,
        
        }
        pub struct CompleteArrayHeader {
        
        
            pub common: Box<CommonArrayHeader>,
        
            pub detail: Box<CompleteTypeDetail>,
        
        }
        pub struct MinimalArrayHeader {
        
        
            pub common: Box<CommonArrayHeader>,
        
        }
        pub struct CompleteArrayType {
        
        
            pub collection_flag: Box<CollectionTypeFlag>,
        
            pub header: Box<CompleteArrayHeader>,
        
            pub element: Box<CompleteCollectionElement>,
        
        }
        pub struct MinimalArrayType {
        
        
            pub collection_flag: Box<CollectionTypeFlag>,
        
            pub header: Box<MinimalArrayHeader>,
        
            pub element: Box<MinimalCollectionElement>,
        
        }
        pub struct CompleteMapType {
        
        
            pub collection_flag: Box<CollectionTypeFlag>,
        
            pub header: Box<CompleteCollectionHeader>,
        
            pub key: Box<CompleteCollectionElement>,
        
            pub element: Box<CompleteCollectionElement>,
        
        }
        pub struct MinimalMapType {
        
        
            pub collection_flag: Box<CollectionTypeFlag>,
        
            pub header: Box<MinimalCollectionHeader>,
        
            pub key: Box<MinimalCollectionElement>,
        
            pub element: Box<MinimalCollectionElement>,
        
        }
        pub type BitBound = u16;
        pub struct CommonEnumeratedLiteral {
        
        
            pub value: i32,
        
            pub flags: Box<EnumeratedLiteralFlag>,
        
        }
        pub struct CompleteEnumeratedLiteral {
        
        
            pub common: Box<CommonEnumeratedLiteral>,
        
            pub detail: Box<CompleteMemberDetail>,
        
        }
        pub type CompleteEnumeratedLiteralSeq = Vec<CompleteEnumeratedLiteral>;
        pub struct MinimalEnumeratedLiteral {
        
        
            pub common: Box<CommonEnumeratedLiteral>,
        
            pub detail: Box<MinimalMemberDetail>,
        
        }
        pub type MinimalEnumeratedLiteralSeq = Vec<MinimalEnumeratedLiteral>;
        pub struct CommonEnumeratedHeader {
        
        
            pub bit_bound: Box<BitBound>,
        
        }
        pub struct CompleteEnumeratedHeader {
        
        
            pub common: Box<CommonEnumeratedHeader>,
        
            pub detail: Box<CompleteTypeDetail>,
        
        }
        pub struct MinimalEnumeratedHeader {
        
        
            pub common: Box<CommonEnumeratedHeader>,
        
        }
        pub struct CompleteEnumeratedType {
        
        
            pub enum_flags: Box<EnumTypeFlag>,
        
            pub header: Box<CompleteEnumeratedHeader>,
        
            pub literal_seq: Box<CompleteEnumeratedLiteralSeq>,
        
        }
        pub struct MinimalEnumeratedType {
        
        
            pub enum_flags: Box<EnumTypeFlag>,
        
            pub header: Box<MinimalEnumeratedHeader>,
        
            pub literal_seq: Box<MinimalEnumeratedLiteralSeq>,
        
        }
        pub struct CommonBitflag {
        
        
            pub position: u16,
        
            pub flags: Box<BitflagFlag>,
        
        }
        pub struct CompleteBitflag {
        
        
            pub common: Box<CommonBitflag>,
        
            pub detail: Box<CompleteMemberDetail>,
        
        }
        pub type CompleteBitflagSeq = Vec<CompleteBitflag>;
        pub struct MinimalBitflag {
        
        
            pub common: Box<CommonBitflag>,
        
            pub detail: Box<MinimalMemberDetail>,
        
        }
        pub type MinimalBitflagSeq = Vec<MinimalBitflag>;
        pub struct CommonBitmaskHeader {
        
        
            pub bit_bound: Box<BitBound>,
        
        }
        pub type CompleteBitmaskHeader = CompleteEnumeratedHeader;
        pub type MinimalBitmaskHeader = MinimalEnumeratedHeader;
        pub struct CompleteBitmaskType {
        
        
            pub bitmask_flags: Box<BitmaskTypeFlag>,
        
            pub header: Box<CompleteBitmaskHeader>,
        
            pub flag_seq: Box<CompleteBitflagSeq>,
        
        }
        pub struct MinimalBitmaskType {
        
        
            pub bitmask_flags: Box<BitmaskTypeFlag>,
        
            pub header: Box<MinimalBitmaskHeader>,
        
            pub flag_seq: Box<MinimalBitflagSeq>,
        
        }
        pub struct CommonBitfield {
        
        
            pub position: u16,
        
            pub flags: Box<BitsetMemberFlag>,
        
            pub bitcount: u8,
        
            pub holder_type: Box<TypeKind>,
        
        }
        pub struct CompleteBitfield {
        
        
            pub common: Box<CommonBitfield>,
        
            pub detail: Box<CompleteMemberDetail>,
        
        }
        pub type CompleteBitfieldSeq = Vec<CompleteBitfield>;
        pub struct MinimalBitfield {
        
        
            pub common: Box<CommonBitfield>,
        
            pub name_hash: Box<NameHash>,
        
        }
        pub type MinimalBitfieldSeq = Vec<MinimalBitfield>;
        pub struct CompleteBitsetHeader {
        
        
            pub detail: Box<CompleteTypeDetail>,
        
        }
        pub struct MinimalBitsetHeader {
        
        
        }
        pub struct CompleteBitsetType {
        
        
            pub bitset_flags: Box<BitsetTypeFlag>,
        
            pub header: Box<CompleteBitsetHeader>,
        
            pub field_seq: Box<CompleteBitfieldSeq>,
        
        }
        pub struct MinimalBitsetType {
        
        
            pub bitset_flags: Box<BitsetTypeFlag>,
        
            pub header: Box<MinimalBitsetHeader>,
        
            pub field_seq: Box<MinimalBitfieldSeq>,
        
        }
        pub struct CompleteExtendedType {
        
        
        }
        pub struct CompleteTypeObject {
            pub _d: u8,
        
            pub alias_type: Option<Box<CompleteAliasType>>,
        
            pub annotation_type: Option<Box<CompleteAnnotationType>>,
        
            pub struct_type: Option<Box<CompleteStructType>>,
        
            pub union_type: Option<Box<CompleteUnionType>>,
        
            pub bitset_type: Option<Box<CompleteBitsetType>>,
        
            pub sequence_type: Option<Box<CompleteSequenceType>>,
        
            pub array_type: Option<Box<CompleteArrayType>>,
        
            pub map_type: Option<Box<CompleteMapType>>,
        
            pub enumerated_type: Option<Box<CompleteEnumeratedType>>,
        
            pub bitmask_type: Option<Box<CompleteBitmaskType>>,
        
            pub extended_type: Option<Box<CompleteExtendedType>>,
        
        }
        pub struct MinimalExtendedType {
        
        
        }
        pub struct MinimalTypeObject {
            pub _d: u8,
        
            pub alias_type: Option<Box<MinimalAliasType>>,
        
            pub annotation_type: Option<Box<MinimalAnnotationType>>,
        
            pub struct_type: Option<Box<MinimalStructType>>,
        
            pub union_type: Option<Box<MinimalUnionType>>,
        
            pub bitset_type: Option<Box<MinimalBitsetType>>,
        
            pub sequence_type: Option<Box<MinimalSequenceType>>,
        
            pub array_type: Option<Box<MinimalArrayType>>,
        
            pub map_type: Option<Box<MinimalMapType>>,
        
            pub enumerated_type: Option<Box<MinimalEnumeratedType>>,
        
            pub bitmask_type: Option<Box<MinimalBitmaskType>>,
        
            pub extended_type: Option<Box<MinimalExtendedType>>,
        
        }
        pub struct TypeObject {
            pub _d: u8,
        
            pub complete: Option<Box<CompleteTypeObject>>,
        
            pub minimal: Option<Box<MinimalTypeObject>>,
        
        }
        pub type TypeObjectSeq = Vec<TypeObject>;
        pub type StronglyConnectedComponent = TypeObjectSeq;
        pub struct TypeIdentifierTypeObjectPair {
        
        
            pub type_identifier: Box<TypeIdentifier>,
        
            pub type_object: Box<TypeObject>,
        
        }
        pub type TypeIdentifierTypeObjectPairSeq = Vec<TypeIdentifierTypeObjectPair>;
        pub struct TypeIdentifierPair {
        
        
            pub type_identifier1: Box<TypeIdentifier>,
        
            pub type_identifier2: Box<TypeIdentifier>,
        
        }
        pub type TypeIdentifierPairSeq = Vec<TypeIdentifierPair>;
        pub struct TypeIdentifierWithSize {
        
        
            pub type_id: Box<TypeIdentifier>,
        
            pub typeobject_serialized_size: u32,
        
        }
        pub type TypeIdentifierWithSizeSeq = Vec<TypeIdentifierWithSize>;
        pub struct TypeIdentifierWithDependencies {
        
        
            pub typeid_with_size: Box<TypeIdentifierWithSize>,
        
            pub dependent_typeid_count: i32,
        
            pub dependent_typeids: Vec<TypeIdentifierWithSize>,
        
        }
        pub type TypeIdentifierWithDependenciesSeq = Vec<TypeIdentifierWithDependencies>;
        pub struct TypeInformation {
        
        
            pub minimal: Box<TypeIdentifierWithDependencies>,
        
            pub complete: Box<TypeIdentifierWithDependencies>,
        
        }
        pub type TypeInformationSeq = Vec<TypeInformation>;
    }
}
