#progma xidlc package xidlc
#progma xidlc version v1.0.0

interface HttpResponseShapeService {
    string hello();

    void get_count(
        out long count
    );

    long add(
        in long a,
        in long b,
        out long sum
    );

    long bump(
        inout long value
    );

    void ping();
};
