#progma xidlc package xidlc
#progma xidlc version v1.0.0

@derive(Debug, Serialize, Deserialize)
struct CreateUserRequest {
    string name;
    uint32 age;
};

interface HttpDefaultsService {
    string get_name(
        @query string name
    );

    @get
    string list_orders(
        @path("uid") uint32 user_id,
        uint32 page,
        uint32 size
    );

    @post(path = "/users")
    string create_user(
        CreateUserRequest req
    );

    @post(path = "/users/search")
    string search_user(
        string name,
        uint32 age
    );

    @get(path = "/v1/users/{id}")
    string get_user(
        uint32 id,
        @query string lang
    );

    string get_user_alias(
        @path("id") uint32 user_id,
        @query("lang") string locale
    );
};
