module city {
    interface StreamApi {
        @server-stream
        void watch_alert(in string district, out string message);

        @client-stream
        void upload_sensor(in string sensor_id, in long value);

        @bidi-stream
        void chat(in string room_id, in string text, out string from, out string body);

        @server-stream
        readonly attribute string status;
    };
};
