#progma xidlc package xidlc
#progma xidlc version v1.0.0

@http-basic
@api-key(in = "header", name = "X-Org-Key")
interface HttpSecurityInheritanceService {
    @get(path = "/reports/{id}")
    string get_report(@path("id") string id);

    @oauth2(scopes = ["reports:write"])
    @post(path = "/reports/{id}")
    string update_report(
        @path("id") string id,
        string body
    );

    @no-security
    @get(path = "/health")
    string health();
};
