module test {
    struct User {
        uint32 id;
        @http(rename = "full_name")
        string name;
    };

    interface HeaderService {
        @get(path = "/v1/headers/{id}")
        User get_user(
            @path("id") uint32 id,
            @header("X-Req-Id") string req_id,
            @header("X-Flags") sequence<string> flags,
            @header("X-Age") uint32 age,
            @cookie("sid") string session_id,
            @cookie("pref") sequence<string> prefs
        );

        @post(path = "/v1/headers")
        void create_user(
            @header("X-Token") string token,
            @cookie("sid") string session_id,
            string name
        );
    };
};
