
struct ArtifactHir {
    string lang;
    ::xidl_parser::hir::Specification hir;
    ::xidl_parser::hir::ParserProperties props;
};


struct ArtifactFile {
    string path;
    string content;
};


enum ArtifactKind {
    @default_literal
    Hir,
    File
};


union Artifact switch (ArtifactKind) {
    case ArtifactKind::Hir:
        ArtifactHir hir;
    case ArtifactKind::File:
        ArtifactFile file;
};

interface Codegen {
    string get_engine_version();
    ::xidl_parser::hir::ParserProperties get_properties();
    sequence<Artifact> generate(
        in ::xidl_parser::hir::Specification hir,
        in string path,
        in ::xidl_parser::hir::ParserProperties props
    );
};
