//! Generated by xidlc.
#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unreachable_patterns)]
#![allow(clippy::let_unit_value)]

use std::collections::BTreeMap;
pub trait HelloWorld {
    async fn sayHello(&self, name: String) -> Result<(), xidl_rust_axum::Error>;
}

use std::sync::Arc;
use xidl_rust_axum::axum::{
    extract::{Path, Query},
    http::StatusCode,
    response::IntoResponse,
    routing::{delete, get, head, options, patch, post, put},
    Json, Router,
};
use xidl_rust_axum::serde::{Deserialize, Serialize};
#[derive(Serialize, Deserialize)]
struct HelloWorldSayHelloBody {
    name: String,
}

pub struct HelloWorldServer<T> {
    inner: Arc<T>,
}

impl<T> HelloWorldServer<T>
where
    T: HelloWorld + Send + Sync + 'static,
{
    pub fn new(inner: T) -> Self {
        Self {
            inner: Arc::new(inner),
        }
    }

    pub fn router(self) -> Router {
        let mut router = Router::new();
        let svc = self.inner;
        router = router.route(
            "/hello",
            post({
                let svc = svc.clone();
                move |Json(body): Json<HelloWorldSayHelloBody>| async move {
                    let HelloWorldSayHelloBody { name } = body;
                    let result = svc.sayHello(name).await;
                    match result {
                        Ok(value) => (StatusCode::OK, Json(value)).into_response(),
                        Err(err) => err.into_response(),
                    }
                }
            }),
        );
        router
    }
}

impl<T> xidl_rust_axum::Service for HelloWorldServer<T>
where
    T: HelloWorld + Send + Sync + 'static,
{
    fn into_router(self) -> Router {
        self.router()
    }
}

pub fn service<T>(inner: T) -> HelloWorldServer<T>
where
    T: HelloWorld + Send + Sync + 'static,
{
    HelloWorldServer::new(inner)
}

pub struct HelloWorldClient {
    client: xidl_rust_axum::Client,
}

impl HelloWorldClient {
    pub fn new(base_url: impl Into<String>) -> Self {
        Self {
            client: xidl_rust_axum::Client::new(base_url),
        }
    }
}

impl HelloWorld for HelloWorldClient {
    async fn sayHello(&self, name: String) -> Result<(), xidl_rust_axum::Error> {
        let mut path = "/hello".to_string();
        let url = self.client.url(&path);
        let mut req = self
            .client
            .http()
            .request(xidl_rust_axum::reqwest::Method::POST, url);
        let body = HelloWorldSayHelloBody { name };
        req = req.json(&body);
        let resp = req
            .send()
            .await
            .map_err(|err| xidl_rust_axum::Error::new(500, err.to_string()))?;
        if resp.status().is_success() {
            resp.json::<()>()
                .await
                .map_err(|err| xidl_rust_axum::Error::new(500, err.to_string()))
        } else {
            let status = resp.status();
            let body = resp.json::<xidl_rust_axum::ErrorBody>().await.ok();
            let err = match body {
                Some(body) => xidl_rust_axum::Error::new(body.code, body.msg),
                None => xidl_rust_axum::Error::new(500, format!("http error: {}", status.as_u16())),
            };
            Err(err)
        }
    }
}
