interface Hysteria2 {
    @post(path = "auth")
    void auth(
        /// Authentication credentials.
        @header
        @rename("Hysteria-Auth")
        string auth,
        /// Client's maximum receive rate in bytes per second. A value of 0 indicates unknown.
        @header
        @rename("Hysteria-CC-RX")
        uint32 rx,
        /// A random padding string of variable length.
        @header
        @rename("Hysteria-Padding")
        string padding,
        /// Whether the server supports UDP relay.
        @header
        @rename("Hysteria-UDP")
        out boolean udp,
        @header
        @rename("Hysteria-CC-RX")
        out uint32 rx,
        @header
        @rename("Hysteria-Padding")
        out string padding
    );

};
