#pragma xidlc package Smart City JSON-RPC Stream APIs
#pragma xidlc version v1.0.0

enum PacketKind {
    HEARTBEAT,
    DATA,
};

union Packet switch (PacketKind) {
    case PacketKind::HEARTBEAT:
        long seq;
    case PacketKind::DATA:
        string payload;
};

interface CityJsonrpcStreamApi {
    @server_stream
    void alerts(
        in string district,
        out string message
    );

    @client_stream
    void upload_sensor(
        in string sensor_id,
        in long value
    );

    @bidi_stream
    void chat(
        in string room_id,
        in string text,
        out string from,
        out string text
    );

    @bidi_stream
    Packet packet_stream(in Packet req);

    @server_stream
    readonly attribute string ops_notice;
};
