// Code generated by xidlc-v0.71.0-snapshot. DO NOT EDIT.

package rest_media_types

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/gin-gonic/gin"
	xidlgohttp "github.com/xidl/xidl/golang/xidl-go-rest"
)

var (
	_ = bytes.Buffer{}
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strings.TrimSpace
)

type RestMediaTypesApiService interface {
	SubmitProfile(ctx context.Context, req *RestMediaTypesApiSubmitProfileRequest) (*RestMediaTypesApiSubmitProfileResponse, error)
	GetMsgpackUser(ctx context.Context, req *RestMediaTypesApiGetMsgpackUserRequest) (*RestMediaTypesApiGetMsgpackUserResponse, error)
}

func RegisterRestMediaTypesApiHandler(r gin.IRouter, svc RestMediaTypesApiService) {
	r.POST("/v1/forms/profile", func(c *gin.Context) {
		if err := xidlgohttp.GinRequireAccept(c, "application/json"); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusNotAcceptable, "NOT_ACCEPTABLE", err.Error())
			return
		}
		if err := xidlgohttp.GinRequireContentType(c, "application/x-www-form-urlencoded"); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusUnsupportedMediaType, "UNSUPPORTED_MEDIA_TYPE", err.Error())
			return
		}

		req := &RestMediaTypesApiSubmitProfileRequest{}
		body := RestMediaTypesApiSubmitProfileRequestBody{}
		if err := xidlgohttp.GinDecodeBody(c, "application/x-www-form-urlencoded", &body); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusBadRequest, "BAD_REQUEST", err.Error())
			return
		}
		req.Name = body.Name
		req.Age = body.Age
		resp, err := svc.SubmitProfile(c.Request.Context(), req)
		if err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusInternalServerError, "INTERNAL", err.Error())
			return
		}

		respBody := RestMediaTypesApiSubmitProfileResponseBody{
			Return:         resp.Return,
			NormalizedName: resp.NormalizedName,
		}
		if err := xidlgohttp.GinEncodeBody(c, "application/json", respBody); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusInternalServerError, "ENCODE", err.Error())
		}
	})
	r.GET("/v1/msgpack/users/:user_id", func(c *gin.Context) {
		if err := xidlgohttp.GinRequireAccept(c, "application/msgpack"); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusNotAcceptable, "NOT_ACCEPTABLE", err.Error())
			return
		}

		req := &RestMediaTypesApiGetMsgpackUserRequest{}

		if value, err := xidlgohttp.GinPathString(c, "user_id"); err == nil {
			req.UserId = value
		} else {
			xidlgohttp.GinWriteJSONError(c, http.StatusBadRequest, "BAD_REQUEST", err.Error())
			return
		}
		resp, err := svc.GetMsgpackUser(c.Request.Context(), req)
		if err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusInternalServerError, "INTERNAL", err.Error())
			return
		}

		respBody := RestMediaTypesApiGetMsgpackUserResponseBody{
			Return: resp.Return,
			Score:  resp.Score,
		}
		if err := xidlgohttp.GinEncodeBody(c, "application/msgpack", respBody); err != nil {
			xidlgohttp.GinWriteJSONError(c, http.StatusInternalServerError, "ENCODE", err.Error())
		}
	})
}

type RestMediaTypesApiClient struct {
	baseURL    string
	httpClient *http.Client
	auth       xidlgohttp.ClientAuth
}

func NewRestMediaTypesApiClient(baseURL string, httpClient *http.Client, auth xidlgohttp.ClientAuth) *RestMediaTypesApiClient {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &RestMediaTypesApiClient{baseURL: strings.TrimRight(baseURL, "/"), httpClient: httpClient, auth: auth}
}

func (c *RestMediaTypesApiClient) SubmitProfile(ctx context.Context, req *RestMediaTypesApiSubmitProfileRequest) (*RestMediaTypesApiSubmitProfileResponse, error) {
	requestURL := c.baseURL + formatRestMediaTypesApiSubmitProfilePath(req)
	body := RestMediaTypesApiSubmitProfileRequestBody{
		Name: req.Name,
		Age:  req.Age,
	}
	var requestBody bytes.Buffer
	if err := xidlgohttp.MustCodecForMime("application/x-www-form-urlencoded").Encode(&requestBody, body); err != nil {
		return nil, err
	}
	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, &requestBody)
	if err != nil {
		return nil, err
	}
	httpReq.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	httpReq.Header.Set("Accept", "application/json")
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("http %d", resp.StatusCode)
	}
	decoded, err := decodeRestMediaTypesApiSubmitProfileResponse(resp)
	if err != nil {
		return nil, err
	}
	return &decoded, nil
}

func (c *RestMediaTypesApiClient) GetMsgpackUser(ctx context.Context, req *RestMediaTypesApiGetMsgpackUserRequest) (*RestMediaTypesApiGetMsgpackUserResponse, error) {
	requestURL := c.baseURL + formatRestMediaTypesApiGetMsgpackUserPath(req)
	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, err
	}
	httpReq.Header.Set("Accept", "application/msgpack")
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("http %d", resp.StatusCode)
	}
	decoded, err := decodeRestMediaTypesApiGetMsgpackUserResponse(resp)
	if err != nil {
		return nil, err
	}
	return &decoded, nil
}

type RestMediaTypesApiSubmitProfileRequest struct {
	Name string `json:"name" form:"name"`
	Age  uint32 `json:"age" form:"age"`
}

type RestMediaTypesApiSubmitProfileRequestBody struct {
	Name string `json:"name" form:"name"`
	Age  uint32 `json:"age" form:"age"`
}

type RestMediaTypesApiSubmitProfileResponse struct {
	Return         string `json:"return"`
	NormalizedName string `json:"normalized_name"`
}

type RestMediaTypesApiSubmitProfileResponseBody struct {
	Return         string `json:"return"`
	NormalizedName string `json:"normalized_name"`
}

func RestMediaTypesApiSubmitProfileSecurityRequirements() []xidlgohttp.SecurityRequirement {
	return []xidlgohttp.SecurityRequirement{}
}

func RestMediaTypesApiSubmitProfileDeprecated() xidlgohttp.DeprecatedInfo {
	return xidlgohttp.DeprecatedInfo{
		Deprecated: false,
	}
}

func formatRestMediaTypesApiSubmitProfilePath(req *RestMediaTypesApiSubmitProfileRequest) string {
	path := "/v1/forms/profile"
	return path
}
func decodeRestMediaTypesApiSubmitProfileResponse(resp *http.Response) (RestMediaTypesApiSubmitProfileResponse, error) {
	out := RestMediaTypesApiSubmitProfileResponse{}
	body := RestMediaTypesApiSubmitProfileResponseBody{}
	if err := xidlgohttp.MustCodecForMime("application/json").Decode(resp.Body, &body); err != nil {
		return out, err
	}
	out.Return = body.Return
	out.NormalizedName = body.NormalizedName
	return out, nil
}

type RestMediaTypesApiGetMsgpackUserRequest struct {
	UserId string `json:"user_id" form:"user_id"`
}

type RestMediaTypesApiGetMsgpackUserResponse struct {
	Return string `json:"return"`
	Score  uint32 `json:"score"`
}

type RestMediaTypesApiGetMsgpackUserResponseBody struct {
	Return string `json:"return"`
	Score  uint32 `json:"score"`
}

func RestMediaTypesApiGetMsgpackUserSecurityRequirements() []xidlgohttp.SecurityRequirement {
	return []xidlgohttp.SecurityRequirement{}
}

func RestMediaTypesApiGetMsgpackUserDeprecated() xidlgohttp.DeprecatedInfo {
	return xidlgohttp.DeprecatedInfo{
		Deprecated: false,
	}
}

func formatRestMediaTypesApiGetMsgpackUserPath(req *RestMediaTypesApiGetMsgpackUserRequest) string {
	path := "/v1/msgpack/users/{user_id}"
	path = strings.ReplaceAll(path, "{user_id}", req.UserId)
	path = strings.ReplaceAll(path, "{*user_id}", req.UserId)
	return path
}
func decodeRestMediaTypesApiGetMsgpackUserResponse(resp *http.Response) (RestMediaTypesApiGetMsgpackUserResponse, error) {
	out := RestMediaTypesApiGetMsgpackUserResponse{}
	body := RestMediaTypesApiGetMsgpackUserResponseBody{}
	if err := xidlgohttp.MustCodecForMime("application/msgpack").Decode(resp.Body, &body); err != nil {
		return out, err
	}
	out.Return = body.Return
	out.Score = body.Score
	return out, nil
}
