@rust_serde(rename_all = "camelCase")
@rust_inline
struct User {
    @rust_serde(rename = "userId")
    string user_id;
};

@rust_repr(u8)
@rust_non_exhaustive
enum Color {
    @rust_deprecated(note = "primary red")
    Red,
    Green
};

@rust_allow(async_fn_in_trait)
interface Api {
    @rust_cfg(feature = "client")
    void ping();
};
