@rust-serde(rename_all = "camelCase")
@rust-inline
struct User {
    @rust-serde(rename = "userId")
    string user_id;
};

@rust-repr(u8)
@rust-non_exhaustive
enum Color {
    @rust-deprecated(note = "primary red")
    Red,
    Green
};

@rust-allow(async_fn_in_trait)
interface Api {
    @rust-cfg(feature = "client")
    void ping();
};
