@derive(Serialize, Deserialize)
enum Tag {
    V1,
    V2,
    V3,
};

@derive(Serialize, Deserialize)
union UnionValue switch (Tag) {
    case Tag::V1:
        int case1;
    case Tag::V2:
        sequence<string> case2;
    case Tag::V3:
        map<string, string> case3;
};

@derive(Serialize, Deserialize)
union IntTagValue switch (long) {
    case 1:
        string one;
    case 2:
    case 3:
        int two_or_three;
    default:
        boolean fallback;
};

@derive(Serialize, Deserialize)
union BoolTagValue switch (boolean) {
    case TRUE:
        string yes;
    case FALSE:
        string no;
};

@derive(Serialize, Deserialize)
union CharTagValue switch (char) {
    case 'x':
        string ex;
    case 'y':
        string why;
    default:
        string other;
};
