// method
@annotation get {
    string path default "";
};

@annotation post {
    string path default "";
};

@annotation put {
    string path default "";
};

@annotation delete {
    string path default "";
};

@annotation patch {
    string path default "";
};

// op params
@annotation path {
};

@annotation query {
};

@annotation header {
};

@annotation cookie {
};

@annotation body {
};

// interface, op
@annotation cors {
    sequence<string> site;
};

// interface, op
@annotation deprecated {
    string since default "";
    string after default ""; // optional
};

// interface, op
@annotation request {
    string format;
};

// interface, op
@annotation response {
    string format;
};

@annotation upgrade {
    string protocol;
};
