name: build-docs

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.11.0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: 'pnpm'
          cache-dependency-path: website/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: website

      - name: Build docs
        run: pnpm build
        working-directory: website
        env:
          GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
