name: check-unittest

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: golang/xidlc-examples/go.mod
          cache: true

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Make test-go
        run: |
          make test-go

      - name: Cargo test
        run: |
          make test
