name: check-unittest

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.92.0
        with:
          components: rustfmt, clippy

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: golang/xidlc-examples/go.mod
          cache: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install pre-commit
        run: |
          python3 -m pip install pre-commit

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Install taplo
        uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli

      - name: Pre-commit
        run: |
          pre-commit run -a

      - name: Cargo clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Python compile
        run: |
          python3 -m compileall python

      - name: Cargo test
        run: |
          make test

      - name: Python test
        run: |
          make -C python test

      - name: Check release
        run: |
          cargo publish --workspace --dry-run
