name: check-unittest

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: xidl-playground/pnpm-lock.yaml

      - name: Install playground deps
        run: pnpm install --frozen-lockfile
        working-directory: xidl-playground

      - name: Cargo test
        run: |
          cargo test --all

      - name: Buld Wasm
        run: |
          sh scripts/build-wasm.sh

      - name: Build playground
        run: pnpm build
        working-directory: xidl-playground
