name: publish-npm

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Publish package
        working-directory: typescript/xidl-typescript-codec/
        run: npm publish --registry=https://registry.npmjs.org/ --access public
