# Code generated by xidlc-v0.77.0-53afdf5e. DO NOT EDIT.

from __future__ import annotations

import abc
import enum
from dataclasses import dataclass, field
from typing import Any, Optional

# generated module: http_security
